# Dat_gen function 
Dat_gen <- function(n, beta, Rho){
  #n: total number of subjects in phase I
  #beta: log odds ratio
  #theta: known odds ratios for x1,x2,x3 (Yaqi:no theta?)
  #p0: pre-specified probability of being selected into phase II for Y=0,G=g (Yaqi:G=g?)
  #ratio: pre-specified number of controls relative to cases
  # Phase I sample
  if (Rho == "Independent")
  {x1 <- rnorm(n)
  z <- rnorm(n)}
  if (Rho == "0.3")
  {sigma <- matrix(c(1, 0.3, 0.3, 1), nrow=2, byrow=TRUE) #0.3*sqrt(1)*sqrt(1)
  x1z <- rmvnorm(n, mean=c(0, 0), sigma=sigma)
  x1 <- x1z[,1]
  z <- x1z[,2]
  #cor(x1,z)
  }
  if (Rho == "0.5")
  {sigma <- matrix(c(1, 0.5, 0.5, 1), nrow=2, byrow=TRUE)
  x1z <- rmvnorm(n, mean=c(0, 0), sigma=sigma)
  x1 <- x1z[,1]
  z <- x1z[,2]
  #cor(x1,z)
  }
  x2 <- runif(n)
  x3 <- rbinom(n, size=1, prob=0.2)
  X <- cbind(rep(1,n), x1, x2, x3, z)
  y <- rbinom(n, size=1, prob=exp(X %*% beta)/(1+exp(X %*% beta)))
  dat <- data.frame(cbind(y,x1,x2,x3,z))
  dat$id <- 1:n
  dat_case <- dat[dat$y==1, ]
  dat_con <- dat[dat$y==0, ]
  dat_ol <- dat[, c("y", "x1", "x2", "x3", "id")]
  dat_ol_case <- dat_ol[dat_ol$y==1, ]
  dat_ol_con <- dat_ol[dat_ol$y==0, ]
  return(list(dat = dat, dat_ol = dat_ol))
}

#2.3 Generate Phase II data with E-balanced Design
Dat_genR <- function(dat, n, beta, numG, p0, ratio){
  #n: total number of subjects in phase I
  #beta: odds ratio
  #numG: number of stratum defined by variables x1,x2,x3
  #p0: pre-specified probability of being selected into phase II for Y=0,G=g
  #ratio: pre-spefified number of controls relative to cases
  dat_case <- dat[dat$y==1, ]
  dat_con <- dat[dat$y==0, ]
  # Phase II sample
  dat2_con <- NULL
  x0 <- xtabs(~dat$y+dat$G)[2,]*ratio
  for (i in 1:numG){
    dat_con_i <- dat_con[dat_con$G==i, ]
    selected_con <- 0
    tot_con <- 1
    ## controls for stratum G=i
    while (tot_con <= nrow(dat_con_i) & selected_con < x0[i]){
      choice <- rbinom(1, size=1, prob=p0[i])
      if (choice==1){
        dat2_con <- rbind(dat2_con, dat_con_i[tot_con, ])
        selected_con <- selected_con + 1
      }
      tot_con <- tot_con + 1
    }
  }
  dat2 <- rbind(dat_case, dat2_con)
  dat2
}

#For data with stratum G (e.g. data generated by BD and E-balanced design or G constructed by post-stratification)
Dat_formatG <- function(dat, dat2, method){
  #data_list: data generated by Dat_gen;
  #method: MLE/PL/Benchmark
  
  if (method=="MLE"){
    nonDeath <- aggregate(1-dat$y, by=list(G=dat$G, x1=dat$x1, x2=dat$x2, x3=dat$x3, z=dat$z), FUN=sum)$x
    dat1.mle <- data.frame(aggregate(dat$y, by=list(G=dat$G, x1=dat$x1, x2=dat$x2, x3=dat$x3, z=dat$z), FUN=sum))
    dat1.mle <- data.frame(cbind(dat1.mle, nonDeath))
    names(dat1.mle) <- c("G","x1","x2","x3","z", "Death","nonDeath")
    
    conts <- aggregate(1-dat2$y, by=list(G=dat2$G, x1=dat2$x1, x2=dat2$x2, x3=dat2$x3, z=dat2$z), FUN=sum)$x
    dat2.mle <- data.frame(aggregate(dat2$y, by=list(G=dat2$G, x1=dat2$x1, x2=dat2$x2, x3=dat2$x3, z=dat2$z), FUN=sum))
    dat2.mle <- data.frame(cbind(dat2.mle, conts))
    names(dat2.mle) <- c("G","x1","x2","x3","z","cases","conts")
    
    # Final = Phase I + Phase II
    fdat.mle <- merge(dat1.mle, dat2.mle, by=c("G","x1","x2","x3","z"), all=T)
    fdat.mle$cases <- ifelse(is.na(fdat.mle$cases), 0, fdat.mle$cases)
    fdat.mle$conts <- ifelse(is.na(fdat.mle$conts), 0, fdat.mle$conts)
    
    # Estimate u_ig = n_ig/N_ig
    nn1 <- aggregate(dat$y, by=list(G=dat$G), FUN=sum)$x
    nn0 <- aggregate(1-dat$y, by=list(G=dat$G), FUN=sum)$x
    n1 <- aggregate(dat2$y, by=list(G=dat2$G), FUN=sum)$x
    n0 <- aggregate(1-dat2$y, by=list(G=dat2$G), FUN=sum)$x
    
    w1 <- round(n1/nn1, 3)
    w0 <- round(n0/nn0, 3)
    mu_1 <- sapply(fdat.mle$G, function(x) w1[x])
    mu_0 <- sapply(fdat.mle$G, function(x) w0[x])
    return(list(fdat.mle=fdat.mle, dat2.mle=dat2.mle, dat1.mle=dat1.mle, dat=dat, w1=w1, w0=w0, mu_1=mu_1, mu_0=mu_0, nn0=nn0, nn1=nn1, n0=n0, n1=n1,  dat2_orig = dat2))
  }
}

#3. Estimation - with G
#Fit Two-Phase maximum likelihood model (With G)
Dat_mleFit_new <- function(data_list){
  # data_list: generated by Dat_format("MLE")
  fdat.mle <- data_list$fdat.mle
  dat2.mle <- data_list$dat2.mle
  dat1.mle <- data_list$dat1.mle
  dat <- data_list$dat
  w1 <- data_list$w1
  w0 <- data_list$w0
  mu_1 <- data_list$mu_1
  mu_0 <- data_list$mu_0
  nn0 <- data_list$nn0
  nn1 <- data_list$nn1
  n0 <- data_list$n0
  n1 <- data_list$n1
  case=fdat.mle$cases
  group=fdat.mle$G
  x=cbind(rep(1,nrow(fdat.mle)),fdat.mle$x1,fdat.mle$x2,fdat.mle$x3,fdat.mle$z)
  N=fdat.mle$cases+fdat.mle$conts
  numbeta <- numbeta_new
  mod <- tps(cbind(cases, conts) ~ x1+x2+x3+z, data=fdat.mle, nn0=nn0, nn1=nn1, group=fdat.mle$G, method="ML", cohort=T)
  #beta.mle <- mod$coef
  beta.mle <- mod$coef
  #XX <- cbind(rep(1,nrow(fdat.mle)), fdat.mle$x1, fdat.mle$x2, fdat.mle$x3, fdat.mle$z) # Design matrix
  #yhat.mle <- exp(XX %*% beta.mle)/(1 + exp(XX %*% beta.mle))
  XX2 <- cbind(rep(1,nrow(dat2.mle)), dat2.mle$x1, dat2.mle$x2, dat2.mle$x3, dat2.mle$z)
  yhat2.mle <- exp(XX2 %*% beta.mle)/(1 + exp(XX2 %*% beta.mle))
  gamma_ig <- matrix(NA, 2, numG)
  for(g in 1:numG)
  {
    gamma_ig[1,g] <- 1
    for(itr in 1:40)
    {
      mm1 <- (n1[g]-gamma_ig[1,g])/(nn1[g]-gamma_ig[1,g])
      mm0 <- (n0[g]+gamma_ig[1,g])/(nn0[g]+gamma_ig[1,g])
      gamma_ig[1,g] <- n1[g]-sum(yhat2.mle[which(dat2.mle$G==g)]*mm1/(mm0*(1-yhat2.mle[which(dat2.mle$G==g)])+yhat2.mle[which(dat2.mle$G==g)]*mm1))
      itr=itr+1
    }
  }
  gamma_ig[2,] <- -gamma_ig[1,]
  
  Q_ig <- matrix(NA, 2, numG)
  for(g in 1:numG)
  {
    Q_ig[1,g] <- (nn1[g]-gamma_ig[1,g])/(nn0[g]+nn1[g])
    Q_ig[2,g] <- (nn0[g]-gamma_ig[2,g])/(nn0[g]+nn1[g])
  }
  dat11.mle <- data.frame(count(dat, vars=c("y", "G")))
  
  strata_mat <- matrix(NA, 4, numG)
  for (g in 1:numG)
  {strata_mat[1,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$cases==1))
  strata_mat[2,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$conts==1))
  strata_mat[3,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$Death-fdat.mle$cases==1))
  strata_mat[4,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$nonDeath-fdat.mle$conts==1))}
  
  u_ig <- matrix(NA, 2, numG)
  for (i in 1:2){
    for (g in 1:numG){
      u_ig[i, g] <- 1 - strata_mat[i+2, g]/(sum(strata_mat[,g])*Q_ig[i, g])
      
    }
  }
  
  # All things that we need to calculate based on above information obtained 
  W_g <- numeric(numG)
  B_g <- matrix(NA, numbeta, numG)
  A_g <- matrix(NA, 2, numG)
  p_g <- numeric(numG) #p(G=g)
  for (g in 1:numG){
    #counts <- dat2.mle[dat2.mle$G==g, "counts"]
    counts <- dat2.mle[dat2.mle$G==g, "cases"] + dat2.mle[dat2.mle$G==g, "conts"]
    x1 <- dat2.mle[dat2.mle$G==g, "x1"]
    x2 <- dat2.mle[dat2.mle$G==g, "x2"]
    x3 <- dat2.mle[dat2.mle$G==g, "x3"]
    z <- dat2.mle[dat2.mle$G==g, "z"]
    X <- cbind(rep(1,length(x1)),x1,x2,x3,z) 
    yfit.mle <- yhat2.mle[dat2.mle$G==g]
    u <- c(u_ig[1, g], u_ig[2, g])
    ystar.mle <- u[1]*yfit.mle/(u[1]*yfit.mle+u[2]*(1-yfit.mle))
    
    #W_g
    W_g[g] <- sum(counts*(ystar.mle*(1-ystar.mle)))
    #B_g
    B_g[, g] <- t(X) %*% (counts*ystar.mle*(1-ystar.mle))
    #A_g
    A_g[, g] <- c(1/(strata_mat[1,g]-gamma_ig[1,g])-1/(strata_mat[1,g]+strata_mat[3,g]-gamma_ig[1,g]),
                  1/(strata_mat[2,g]-gamma_ig[2,g])-1/(strata_mat[2,g]+strata_mat[4,g]-gamma_ig[2,g]))    
    #p_g
    p_g[g] <- sum(strata_mat[, g])/sum(strata_mat)
  }
  
  A_0g <- apply(A_g, 2, sum)
  K_g <- 1/A_0g-W_g
  dgamma_1g <- matrix(NA, numbeta, numG)
  for (g in 1:numG){
    dgamma_1g[,g] <- -B_g[,g]/(1-A_0g[g]*W_g[g])
  }
  
  #covariate distribution NPMLE estimates for each strata: f(x1,x2,x3,z,g)=f(x1,x2,x3,z|g)*p(G=g)
  #since x1,x2 are continuous, each unique value will only be counted once
  #f(x1,x2,x3,z,g) is a function of beta
  f.mle <- numeric(nrow(dat2.mle))
  df_g <- matrix(NA, numbeta, nrow(dat2.mle)) #df(x1,x2,x3,z|g)/dbeta 
  df <- matrix(NA, numbeta, nrow(dat2.mle)) #df(x1,x2,x3,z)/dbeta
  s_2 <- matrix(NA, numbeta, nrow(dat2.mle)) #score for R_k=1
  for (k in 1:nrow(dat2.mle)){
    #y <- dat2.mle[k, "y"]
    y <- dat2.mle[k, "cases"]
    x1 <- dat2.mle[k, "x1"]
    x2 <- dat2.mle[k, "x2"]
    x3 <- dat2.mle[k, "x3"]
    z <- dat2.mle[k, "z"]
    #counts <- dat2.mle[k, "counts"]
    counts <- dat2.mle[k, "cases"] + dat2.mle[k, "conts"]
    g <- dat2.mle[k,"G"]
    u <- c(u_ig[1, g], u_ig[2,g])
    yfit.mle <- yhat2.mle[k]
    dgamma <- dgamma_1g[, g]
    a <- A_g[,g]
    f.mle[k] <- counts/(u[1]*yfit.mle+u[2]*(1-yfit.mle))/n
    df_g[,k] <- -counts/(sum(strata_mat[,g])*(u[1]*yfit.mle+u[2]*(1-yfit.mle))^2)*(c(1,x1,x2,x3,z)*yfit.mle*(1-yfit.mle)*(u[1]-u[2])+dgamma*((1-yfit.mle)*u[2]*a[2]-yfit.mle*u[1]*a[1]))
    df[, k] <- df_g[,k]*p_g[g]
    s_2[, k] <- c(1,x1,x2,x3,z)*(y-yfit.mle) + df_g[, k]/f.mle[k]*p_g[g]
  }
  
  s_1 <- matrix(NA, numbeta, nrow(dat11.mle)) #score for R_k=0
  for (k in 1:nrow(dat11.mle)){
    y <- dat11.mle[k, "y"]
    g <- dat11.mle[k, "G"]
    Q <- NULL
    if (y==1){
      Q = Q_ig[1, g]
      s_1[, k] <- -dgamma_1g[, g]/sum(strata_mat[,g])/Q
    }
    else{
      Q = Q_ig[2, g]
      s_1[,k] <- dgamma_1g[, g]/sum(strata_mat[,g])/Q
    }
  }
  #S_1 <- apply(rbind(s_1, c(strata_mat[4, ], strata_mat[3, ])), 2, function(x) x[1:2]*x[3])
  #S_2 <- apply(rbind(s_2, dat2.mle$cases+dat2.mle$conts), 2, function(x) x[1:2]*x[3])
  #apply(S_2, 1, sum) + apply(S_1, 1, sum)
  
  ## Influence function for odds ratios
  h_1 <- mod$covm %*% s_1*n
  h_2 <- mod$covm %*% s_2*n
  emp_cov <- matrix(0, numbeta, numbeta)
  counts2 <- c(strata_mat[4,], strata_mat[3,])
  for (k in 1:ncol(h_1)){
    emp_cov = emp_cov + h_1[, k] %*% t(h_1[, k])*counts2[k]
  }
  for (k in 1:ncol(h_2)){
    emp_cov = emp_cov + h_2[, k] %*% t(h_2[, k])*(dat2.mle$cases[k]+dat2.mle$conts[k])
  }
  # check emp_cov/(n^2) = mod$covm
  
  return (list(beta.mle=beta.mle, beta.var.mle=diag(mod$covm),beta.var.mle.inf=diag(emp_cov/n^2), h1=h_1, h2=h_2, yhat.mle=yhat2.mle, f.mle=f.mle, df_beta=df, strata_mat=strata_mat))
}

Dat_mleFit_old <- function(dat) {
  n <- nrow(dat)
  
  formula_old <- y ~ x1 + x2 + x3
  mod_old <- glm(formula_old, data = dat, family = binomial(link = "logit"))
  
  beta.full <- coef(mod_old)
  yhat.full <- mod_old$fitted.values
  
  X <- cbind(rep(1, n), dat$x1, dat$x2, dat$x3)
  colnames(X) <- names(beta.full)
  
  S1_beta <- apply(cbind(X, yhat.full), 1, function(row) row[1:4] * (1 - row[5]))
  S0_beta <- apply(cbind(X, yhat.full), 1, function(row) row[1:4] * (0 - row[5]))
  
  W <- diag(as.vector(yhat.full * (1 - yhat.full)))
  I_betabeta <- solve(t(X) %*% W %*% X / n)
  
  h1 <- I_betabeta %*% S1_beta
  h0 <- I_betabeta %*% S0_beta
  
  beta.var.full <- diag(I_betabeta / n)
  
  h_beta_all <- matrix(NA, nrow = length(beta.full), ncol = n)
  h_beta_all[, dat$y == 1] <- h1[, dat$y == 1]
  h_beta_all[, dat$y == 0] <- h0[, dat$y == 0]
  
  h_beta_for_idi_nri <- t(h_beta_all)
  
  return(list(
    h1 = h1,
    h0 = h0,
    yhat.full = yhat.full,
    beta.full = beta.full,
    beta.var.full = beta.var.full,
    model = mod_old,
    beta.mle = beta.full,
    h_beta = h_beta_for_idi_nri,
    h_beta_all = h_beta_all
  ))
}

# ==============================================================================
#      R-balanced 设计参数估计主函数 (多场景批处理版)
# ==============================================================================

# --- 1. 加载与环境设置 ---
require(osDesign)
require(plyr)
require(MESS)
require(mvtnorm)

set.seed(0)

# --- 新增: 定义需要遍历的多个参数级别 ---
prev_levels <- c("Rare", "Moder")
rho_levels <- c("Independent", "0.3", "0.5")
ratio_levels <- c(1, 2)

# 创建一个列表，用于存储所有场景的最终结果
all_results <- list()

# --- 新增: 遍历所有参数组合的外层循环 ---
for (p_val in prev_levels) {
  for (r_val in rho_levels) {
    for (ra_val in ratio_levels) {
      
      # --- 2. 设置当前场景的模拟参数 ---
      Prev <- p_val
      Rho <- r_val
      ratio <- ra_val
      
      # 在控制台打印当前正在运行的场景信息
      cat("\n========================================================\n")
      cat(sprintf("--- 开始运行场景: Prev=%s, Rho=%s, Ratio=%d ---\n", Prev, Rho, ratio))
      cat("========================================================\n\n")
      
      n <- 3000
      if(Prev == "Rare") {
        beta_true <- log(c(0.03, 0.6, 1.6, 0.6, 1.5))
      }
      if(Prev == "Moder") {
        beta_true <- log(c(0.13, 0.6, 1.6, 0.6, 1.5))
      }
      
      numbeta_new <- length(beta_true)
      numG <- 4
      K <- 100  # 每个场景的模拟次数，可按需调整
      
      # --- 3. 为当前场景预计算分层抽样概率 p0 ---
      cat("正在为当前场景预计算分层抽样概率 'p0'...\n")
      x1_init <- rnorm(n)
      x2_init <- runif(n)
      x3_init <- rbinom(n, size=1, prob=0.2)
      z_init <- rnorm(n)
      X_init_full <- cbind(rep(1,n), x1_init, x2_init, x3_init, z_init)
      y_init <- rbinom(n, size=1, prob=exp(X_init_full %*% beta_true)/(1+exp(X_init_full %*% beta_true)))
      dat_init_temp <- data.frame(y=y_init, x1=x1_init, x2=x2_init, x3=x3_init, z=z_init)
      
      glm_fit_init <- glm(y ~ 1 + x1 + x2 + x3, data = dat_init_temp, family = binomial(link = "logit"))
      X_old_init <- model.matrix(y ~ 1 + x1 + x2 + x3, data = dat_init_temp)
      prob_init <- exp(X_old_init %*% glm_fit_init$coefficients) / (1 + exp(X_old_init %*% glm_fit_init$coefficients))
      Quan_init <- unname(quantile(prob_init[dat_init_temp$y == 1], c(0.25, 0.5, 0.75)))
      G_init <- sapply(prob_init, function(x) {
        if (x <= Quan_init[1]) 1
        else if (x > Quan_init[1] && x <= Quan_init[2]) 2
        else if (x > Quan_init[2] && x <= Quan_init[3]) 3
        else 4
      })
      dat_init <- data.frame(y=y_init, G=G_init)
      x0 <- xtabs(~y+G, data=dat_init)[2,]*ratio
      p0 <- round(x0/xtabs(~y+G, data=dat_init)[1,], 3)
      p0[is.nan(p0)] <- 0
      cat("当前场景将使用 p0 向量:", p0, "\n\n")
      
      # --- 4. 初始化用于存储当前场景结果的矩阵 ---
      ResBeta_new <- matrix(NA, K, numbeta_new)
      colnames(ResBeta_new) <- c("Intercept", "beta_x1", "beta_x2", "beta_x3", "beta_z")
      ResVar_new_theoretical <- matrix(NA, K, numbeta_new)
      colnames(ResVar_new_theoretical) <- c("Var_Intercept", "Var_x1", "Var_x2", "Var_x3", "Var_z")
      
      # --- 5. 开始当前场景的模拟循环 (K次迭代) ---
      cat(sprintf("开始对当前场景进行 %d 次模拟迭代...\n", K))
      for(k in 1:K) {
        tryCatch({
          generated_data <- Dat_gen(n, beta_true, Rho)
          dat <- generated_data$dat
          
          glm.fit_k <- glm(y ~ 1 + x1 + x2 + x3, data = dat, family = binomial(link = "logit"))
          X_old_k <- model.matrix(y ~ 1 + x1 + x2 + x3, data = dat)
          prob_k <- exp(X_old_k %*% glm.fit_k$coefficients) / (1 + exp(X_old_k %*% glm.fit_k$coefficients))
          Quan_k <- unname(quantile(prob_k[dat$y == 1], c(0.25, 0.5, 0.75), na.rm = TRUE))
          dat$G <- sapply(prob_k, function(x) {
            if (is.na(x) || x <= Quan_k[1]) 1
            else if (x > Quan_k[1] && x <= Quan_k[2]) 2
            else if (x > Quan_k[2] && x <= Quan_k[3]) 3
            else 4
          })
          
          dat_R_k <- Dat_genR(dat, n, beta_true, numG, p0, ratio)
          dat_mlelist <- Dat_formatG(dat, dat_R_k, "MLE")
          mleFit_list_new <- Dat_mleFit_new(dat_mlelist)
          
          if (!is.null(mleFit_list_new$beta.mle)) {
            ResBeta_new[k, ] <- mleFit_list_new$beta.mle
            ResVar_new_theoretical[k, ] <- mleFit_list_new$beta.var.mle
          }
          
          if(k %% 20 == 0) cat(sprintf("    迭代: %d / %d 已完成.\n", k, K))
          
        }, error = function(e) {
          cat(sprintf("    在第 %d 次迭代中发生错误: %s\n", k, e$message))
        })
      }
      cat("当前场景模拟迭代完成。\n")
      
      # --- 6. 当前场景结果分析与汇总 ---
      mean_beta <- colMeans(ResBeta_new, na.rm = TRUE)
      bias <- mean_beta - beta_true
      empirical_se <- apply(ResBeta_new, 2, sd, na.rm = TRUE)
      mean_theoretical_se <- colMeans(sqrt(ResVar_new_theoretical), na.rm = TRUE)
      
      summary_scenario <- data.frame(
        Prev = Prev,
        Rho = Rho,
        Ratio = ratio,
        参数 = colnames(ResBeta_new),
        真实值 = beta_true,
        估计均值 = mean_beta,
        偏差 = bias,
        经验标准误 = empirical_se,
        理论标准误 = mean_theoretical_se,
        check.names = FALSE
      )
      
      # 将当前场景的结果添加到总列表中
      all_results[[length(all_results) + 1]] <- summary_scenario
      
      cat(sprintf("\n--- 场景: Prev=%s, Rho=%s, Ratio=%d 的结果已保存 ---\n", Prev, Rho, ratio))
    }
  }
}

# --- 7. 【新增】合并并展示所有场景的最终结果 ---
final_summary_table <- do.call(rbind, all_results)

cat("\n\n#########################################################")
cat("\n#              所有模拟场景结果汇总                 #")
cat("\n#########################################################\n\n")

# 打印最终的摘要报告
print(final_summary_table, row.names = FALSE, digits = 4)