Dat_auc_mle_new <- function(data_list, mleFit_list, n){
  #data_list: generated by Dat_format("MLE");
  fdat.mle <- data_list$fdat.mle
  dat1.mle <- data_list$dat1.mle
  dat2.mle <- data_list$dat2.mle
  #mleFit_list: generated by Dat_mleFit(data_list)
  fhat.mle <- mleFit_list$f.mle
  yhat.mle <- mleFit_list$yhat.mle
  beta.mle <- mleFit_list$beta.mle
  numbeta <- length(beta.mle) # Get numbeta from the fitted model
  # influence function for odds ratio
  h1 <- mleFit_list$h1
  h2 <- mleFit_list$h2
  strata_mat <- mleFit_list$strata_mat
  df_beta <- mleFit_list$df_beta
  # calculate auc
  denom_tpr.mle <- sum(yhat.mle*fhat.mle)
  denom_fpr.mle <- sum((1-yhat.mle)*fhat.mle)
  c <- c(seq(0, 1, by=0.01)*max(yhat.mle),1)
  num_tpr.mle <- numeric(length(c))
  num_fpr.mle <- numeric(length(c))
  for (j in 1:length(c)){
    ind <- (yhat.mle>=c[j])
    num_tpr.mle[j] <- sum((yhat.mle*fhat.mle)[ind==1])
    num_fpr.mle[j] <- sum(((1-yhat.mle)*fhat.mle)[ind==1])
  }
  tpr.mle <- num_tpr.mle/denom_tpr.mle
  fpr.mle <- num_fpr.mle/denom_fpr.mle
  auc <- auc(fpr.mle, tpr.mle)
  X <- cbind(rep(1,nrow(dat2.mle)), dat2.mle$x1, dat2.mle$x2, dat2.mle$x3, dat2.mle$z)
  # numerical method for dFPR/dbeta and dTPR/dbeta as a function of c
  # Ensure epsilon_beta matches the dimensions of beta.mle
  epsilon_beta <- abs(beta.mle) / 5
  if(any(epsilon_beta == 0)) { # Handle cases where a beta coefficient might be exactly 0
    epsilon_beta[epsilon_beta == 0] <- 0.001 # Assign a small value
  }
  dFPR_beta <- matrix(0, nrow=numbeta, ncol=length(c))
  dTPR_beta <- matrix(0, nrow=numbeta, ncol=length(c))
  yfit1 <- numeric(nrow(dat2.mle))
  yfit2 <- numeric(nrow(dat2.mle))
  fhat1 <- numeric(nrow(dat2.mle))
  fhat2 <- numeric(nrow(dat2.mle))
  for (i in 1:numbeta){
    tmp1 <- beta.mle
    tmp2 <- beta.mle
    tmp1[i] <- beta.mle[i] + epsilon_beta[i]
    tmp2[i] <- beta.mle[i] - epsilon_beta[i]
    yfit1 <- exp(X %*% tmp1)/(1 + exp(X %*% tmp1))
    yfit2 <- exp(X %*% tmp2)/(1 + exp(X %*% tmp2))
    # df_beta is also dependent on the model, so ensure it's calculated appropriately in mleFit
    # Assuming df_beta has already been calculated correctly in Dat_mleFit for the chosen model.
    # If not, you'd need to re-calculate it here or make df_beta model-specific.
    fhat1 <- fhat.mle + df_beta[i,]*epsilon_beta[i]
    fhat2 <- fhat.mle - df_beta[i,]*epsilon_beta[i]
    num1_tpr <- 0
    num2_tpr <- 0
    num1_fpr <- 0
    num2_fpr <- 0
    denom1_tpr <- sum(yfit1*fhat1)
    denom2_tpr <- sum(yfit2*fhat2)
    denom1_fpr <- sum((1-yfit1)*fhat1)
    denom2_fpr <- sum((1-yfit2)*fhat2)
    for (j in 1:length(c)){
      ind1 <- (yfit1>=c[j])
      ind2 <- (yfit2>=c[j])
      num1_tpr <- sum((yfit1*fhat1)[ind1==1])
      num2_tpr <- sum((yfit2*fhat2)[ind2==1])
      num1_fpr <- sum(((1-yfit1)*fhat1)[ind1==1])
      num2_fpr <- sum(((1-yfit2)*fhat2)[ind2==1])
      dTPR_beta[i,j] <- (num1_tpr/denom1_tpr-num2_tpr/denom2_tpr)/(2*epsilon_beta[i])
      dFPR_beta[i,j] <- (num1_fpr/denom1_fpr-num2_fpr/denom2_fpr)/(2*epsilon_beta[i])
    }
  }
  # calculate influence function for TPR/FPR as a function of c
  mat_tpr_h2.mle <- matrix(0, nrow=nrow(dat2.mle), ncol=length(c))
  mat_fpr_h2.mle <- matrix(0, nrow=nrow(dat2.mle), ncol=length(c))
  for (j in 1:length(c)){
    ind <- (yhat.mle>=c[j])
    mat_tpr_h2.mle[,j] <- fhat.mle*n*yhat.mle*(ind-tpr.mle[j])/denom_tpr.mle
    mat_fpr_h2.mle[,j] <- fhat.mle*n*(1-yhat.mle)*(ind-fpr.mle[j])/denom_fpr.mle
  }
  # calculate the influence function for tpr/fpr
  h1_tpr <- t(h1) %*% dTPR_beta
  h2_tpr <- t(h2) %*% dTPR_beta + mat_tpr_h2.mle
  h1_fpr <- t(h1) %*% dFPR_beta
  h2_fpr <- t(h2) %*% dFPR_beta + mat_fpr_h2.mle
  # calculate the influence function of auc
  h1_auc <- 0-apply(h1_fpr, 1, function(x) auc(tpr.mle, x))+apply(h1_tpr, 1, function(x) auc(fpr.mle, x))
  h2_auc <- 0-apply(h2_fpr, 1, function(x) auc(tpr.mle, x))+apply(h2_tpr, 1, function(x) auc(fpr.mle, x))
  # calculate the variance of auc
  a <- rep(h1_auc, c(strata_mat[4, ], strata_mat[3, ]))
  b <- rep(h2_auc, (dat2.mle$cases+dat2.mle$conts))
  tmp <- c(a, b)
  var_auc <- t(tmp) %*% (tmp)/n^2
  return(list(auc=auc, var_auc=var_auc))
}

Dat_auc_mle_old <- function(data, fullFit_list, X){
  #fullFit_list: generated by Dat_fullFit(data)
  n <- nrow(data)
  h_beta_all <- fullFit_list$h_beta_all # Use the full influence function matrix
  yhat.full <- fullFit_list$yhat.full
  beta.full <- fullFit_list$beta.full
  numbeta <- length(beta.full)
  epsilon_beta <- abs(beta_true[1:4])/5
  #calculate auc
  c <- c(seq(0, 1, by=0.01)*max(yhat.full),1)
  denom_tpr.full <- sum(yhat.full)
  denom_fpr.full <- sum(1-yhat.full)
  num_tpr.full <- numeric(length(c))
  num_fpr.full <- numeric(length(c))
  for (j in 1:length(c)){
    ind <- (yhat.full>=c[j])
    num_tpr.full[j] <- sum(yhat.full[ind==1])
    num_fpr.full[j] <- sum((1-yhat.full)[ind==1])
  }
  tpr.full <- num_tpr.full/denom_tpr.full
  fpr.full <- num_fpr.full/denom_fpr.full
  auc <- auc(fpr.full, tpr.full)
  
  # numerical method for dFPR/dbeta and dTPR/dbeta as a function of c
  dFPR_beta <- matrix(0, nrow=numbeta, ncol=length(c))
  dTPR_beta <- matrix(0, nrow=numbeta, ncol=length(c))
  yfit1 <- numeric(nrow(data))
  yfit2 <- numeric(nrow(data))
  for (i in 1:numbeta){
    tmp1 <- beta.full
    tmp2 <- beta.full
    tmp1[i] <- beta.full[i] + epsilon_beta[i]
    tmp2[i] <- beta.full[i] - epsilon_beta[i]
    yfit1 <- exp(X %*% tmp1)/(1 + exp(X %*% tmp1))
    yfit2 <-  exp(X %*% tmp2)/(1 + exp(X %*% tmp2))
    num1_tpr <- 0
    num2_tpr <- 0
    num1_fpr <- 0
    num2_fpr <- 0
    denom1_tpr <- sum(yfit1)
    denom2_tpr <- sum(yfit2)
    denom1_fpr <- sum(1-yfit1)
    denom2_fpr <- sum(1-yfit2)
    
    for (j in 1:length(c)){
      ind1 <- (yfit1>=c[j])
      ind2 <- (yfit2>=c[j])
      num1_tpr <- sum(yfit1[ind1==1])
      num2_tpr <- sum(yfit2[ind2==1])
      num1_fpr <- sum((1-yfit1)[ind1==1])
      num2_fpr <- sum((1-yfit2)[ind2==1])
      dTPR_beta[i,j] <- (num1_tpr/denom1_tpr-num2_tpr/denom2_tpr)/(2*epsilon_beta[i])
      dFPR_beta[i,j] <- (num1_fpr/denom1_fpr-num2_fpr/denom2_fpr)/(2*epsilon_beta[i])
    }
  }
  
  # calculate influence function for TPR/FPR as a function of c
  mat_tpr.full <- matrix(0, nrow=nrow(data), ncol=length(c))
  mat_fpr.full <- matrix(0, nrow=nrow(data), ncol=length(c))
  for (j in 1:length(c)){
    ind <- (yhat.full>=c[j])
    mat_tpr.full[,j] <- yhat.full*(ind-tpr.full[j])/(denom_tpr.full/n)
    mat_fpr.full[,j] <- (1-yhat.full)*(ind-fpr.full[j])/(denom_fpr.full/n)
  }
  
  # CORRECTED: calculate the influence function for tpr/fpr using h_beta_all
  h_tpr <- t(h_beta_all) %*% dTPR_beta + mat_tpr.full
  h_fpr <- t(h_beta_all) %*% dFPR_beta + mat_fpr.full
  
  # Separate influence functions for cases and controls
  h1_tpr <- h_tpr[data$y == 1, ]
  h0_tpr <- h_tpr[data$y == 0, ]
  h1_fpr <- h_fpr[data$y == 1, ]
  h0_fpr <- h_fpr[data$y == 0, ]
  
  #calcualte influence function for auc
  h1_auc <- 0-apply(h1_fpr, 1, function(x) auc(tpr.full, x))+apply(h1_tpr, 1, function(x) auc(fpr.full, x))
  h0_auc <- 0-apply(h0_fpr, 1, function(x) auc(tpr.full, x))+apply(h0_tpr, 1, function(x) auc(fpr.full, x))
  
  # CORRECTED: calculate variance of AUC
  h_auc_full <- rep(NA, n)
  h_auc_full[data$y == 1] <- h1_auc
  h_auc_full[data$y == 0] <- h0_auc
  var_auc <- var(h_auc_full) / n
  
  return(list(auc=auc, sq_var_auc=sqrt(var_auc)))
}

calculate_expectation_tps <- function(mle_fit_list, data_list, cond_Y) {
  # 从列表中提取所需对象
  beta_model <- mle_fit_list$beta.mle
  yhat_model <- mle_fit_list$yhat.mle# 预测概率 p_hat
  fhat_model <- mle_fit_list$f.mle # 分布函数 dF_hat
  df_dbeta_model <- mle_fit_list$df_beta
  h1_model <- mle_fit_list$h1
  h2_model <- mle_fit_list$h2
  num_beta <- length(beta_model)
  dat2_mle_df <- data_list$dat2.mle
  n_total_phaseI <- nrow(data_list$dat)
  # 1. 计算期望值 E[p|Y=cond_Y]
  p1_cond <- if (cond_Y == 1) yhat_model else (1 - yhat_model)
  denominator_E <- sum(p1_cond * fhat_model)
  numerator_E <- sum(yhat_model * p1_cond * fhat_model)
  E_val <- if (denominator_E != 0) numerator_E / denominator_E else 0
  # 2. 数值计算 ∂E/∂β
  dE_dbeta_val <- numeric(num_beta)
  epsilon_beta <- abs(beta_model) / 1e4
  epsilon_beta[epsilon_beta == 0] <- 1e-6
  # 动态确定公式和设计矩阵
  model_formula <- if (num_beta == 5) as.formula("~ x1 + x2 + x3 + z") else as.formula("~ x1 + x2 + x3")
  XX2_model <- model.matrix(model_formula, data = dat2_mle_df)
  for (j in 1:num_beta) {
    beta_plus <- beta_model; beta_plus[j] <- beta_plus[j] + epsilon_beta[j]
    beta_minus <- beta_model; beta_minus[j] <- beta_minus[j] - epsilon_beta[j]
    yhat_plus <- as.vector(1 / (1 + exp(-XX2_model %*% beta_plus)))
    yhat_minus <- as.vector(1 / (1 + exp(-XX2_model %*% beta_minus)))
    fhat_plus <- fhat_model + df_dbeta_model[j,] * epsilon_beta[j]
    fhat_minus <- fhat_model - df_dbeta_model[j,] * epsilon_beta[j]
    p1_plus_cond <- if (cond_Y == 1) yhat_plus else (1 - yhat_plus)
    p1_minus_cond <- if (cond_Y == 1) yhat_minus else (1 - yhat_minus)
    E_plus <- sum(yhat_plus * p1_plus_cond * fhat_plus) / sum(p1_plus_cond * fhat_plus)
    E_minus <- sum(yhat_minus * p1_minus_cond * fhat_minus) / sum(p1_minus_cond * fhat_minus)
    dE_dbeta_val[j] <- (E_plus - E_minus) / (2 * epsilon_beta[j])
  }
  # 3a. 获取 h1_model (对beta的影响) 的列结构，它与 (Y, G) 组合对应
  dat11_mle_info <- plyr::count(data_list$dat, vars = c("y", "G"))
  
  # 3b. 计算每个 (Y, G) 组合对期望 E 的总体影响
  H_E_by_group <- as.vector(t(h1_model) %*% dE_dbeta_val)
  
  # 3c. 创建一个 2xG 的矩阵来结构化地存储这些分层影响函数，以便后续查找
  numG <- length(data_list$nn1) # 从 data_list 获取分层数量
  H_E_phase1_stratified <- matrix(NA, 
                                  nrow = 2, 
                                  ncol = numG, 
                                  dimnames = list(c("Y=0", "Y=1"), paste0("G=", 1:numG)))
  
  # 3d. 根据 (Y,G) 组合的结构，填充这个矩阵
  for (i in 1:nrow(dat11_mle_info)) {
    y_val <- dat11_mle_info[i, "y"]
    g_val <- dat11_mle_info[i, "G"]
    # y=0 对应矩阵第1行, y=1 对应第2行
    H_E_phase1_stratified[y_val + 1, g_val] <- H_E_by_group[i]
  }
  
  # 3. 计算与分布函数相关的直接影响 φ_F
  phi_F_E_val <- numeric(length(yhat_model))
  if (denominator_E != 0) {
    phi_F_E_val <- (fhat_model * n_total_phaseI / denominator_E) * p1_cond * (yhat_model - E_val)
  }
  # 4. 组合得到该期望值的影响函数 (分为Phase I only 和 Phase II 两部分)
  H_E_phase1 <- as.vector(t(h1_model) %*% dE_dbeta_val)
  H_E_phase2 <- as.vector(t(h2_model) %*% dE_dbeta_val) + phi_F_E_val
  return(list(E_val = E_val, 
              H_E_phase1_stratified = H_E_phase1_stratified, # 【修改点】现在是一个 2xG 矩阵
              H_E_phase2 = H_E_phase2))
}

calculate_expectation_glm <- function(mle_fit_list, dat_full_cohort, cond_Y) {
  # 从列表中提取所需对象
  model_glm <- mle_fit_list$model
  beta_glm <- mle_fit_list$beta.mle
  h_beta_glm <- mle_fit_list$h_beta # H_β, N x p 矩阵
  num_beta <- length(beta_glm)
  pred_risk <- predict(model_glm, type = "response")
  y_full <- dat_full_cohort$y
  n_total <- nrow(dat_full_cohort)
  # 1. 计算期望值 E[p|Y=cond_Y]
  idx_cond <- which(y_full == cond_Y)
  E_val <- mean(pred_risk[idx_cond])
  # 2. 数值计算 ∂E/∂β
  dE_dbeta_val <- numeric(num_beta)
  epsilon_beta <- abs(beta_glm) / 1e5
  epsilon_beta[epsilon_beta == 0] <- 1e-6
  X_glm <- model.matrix(model_glm)
  for (j in 1:num_beta) {
    beta_plus <- beta_glm; beta_plus[j] <- beta_plus[j] + epsilon_beta[j]
    beta_minus <- beta_glm; beta_minus[j] <- beta_minus[j] - epsilon_beta[j]
    pred_plus <- as.vector(1 / (1 + exp(-X_glm %*% beta_plus)))
    pred_minus <- as.vector(1 / (1 + exp(-X_glm %*% beta_minus)))
    E_plus <- mean(pred_plus[idx_cond])
    E_minus <- mean(pred_minus[idx_cond])
    dE_dbeta_val[j] <- (E_plus - E_minus) / (2 * epsilon_beta[j])
  }
  # === 修改开始 ===
  # 3. (已移除) 移除 phi_F0_E_val 的计算，因为其影响被排除
  # p_Y_cond <- mean(y_full == cond_Y)
  # phi_F0_E_val <- numeric(n_total)
  # if (p_Y_cond > 0) {
  #  phi_F0_E_val <- (as.integer(y_full == cond_Y) / p_Y_cond) * (pred_risk - E_val)
  # }
  
  # 4. 仅根据参数不确定性计算总影响函数
  H_E_total <- as.vector(h_beta_glm %*% dE_dbeta_val) # 移除了 "+ phi_F0_E_val"
  # === 修改结束 ===
  return(list(E_val = E_val, H_E_total = H_E_total))
}

Dat_idi_mle_final <- function(data_list, mleFit_list_new, mleFit_list_old, dat) {
  # --- 1. 提取核心对象 (此部分无变化) ---
  n_total <- nrow(dat)
  dat2_mle <- data_list$dat2.mle
  dat2_orig <- data_list$dat2_orig
  
  # --- 2. 计算新/旧模型的 IS 和 IP 及其影响函数 (此部分无变化) ---
  # 注意：这里调用的 calculate_expectation_tps 已经是我们修改后的新版本了
  IS_new_comp <- calculate_expectation_tps(mleFit_list_new, data_list, 1)
  IP_new_comp <- calculate_expectation_tps(mleFit_list_new, data_list, 0)
  
  IS_old_comp <- calculate_expectation_glm(mleFit_list_old, dat, 1)
  IP_old_comp <- calculate_expectation_glm(mleFit_list_old, dat, 0)
  
  # --- 3. 计算 IDI 估计值 (此部分无变化) ---
  IDI_est <- (IS_new_comp$E_val - IS_old_comp$E_val) - (IP_new_comp$E_val - IP_old_comp$E_val)
  
  # ======================= 【修改部分开始】 =======================
  # --- 4. 稳健地重建和组合影响函数 ---
  
  # 初始化一个N维向量用于存储总影响函数，并用ID命名以保证对齐
  H_IDI_total <- numeric(n_total)
  names(H_IDI_total) <- dat$id
  
  # 4a. 获取旧模型的总影响函数 (此部分无变化)
  H_IS_old_total <- IS_old_comp$H_E_total
  H_IP_old_total <- IP_old_comp$H_E_total
  names(H_IS_old_total) <- dat$id
  names(H_IP_old_total) <- dat$id
  
  # 4b. 新建一个N维向量用于存储新模型的总影响函数 (此部分无变化)
  H_IS_new_total <- numeric(n_total)
  H_IP_new_total <- numeric(n_total)
  names(H_IS_new_total) <- dat$id
  names(H_IP_new_total) <- dat$id
  
  # --- 【核心修改】替换原有的 4c 和 4d 逻辑 ---
  
  # 4c (新). 为 Phase-I 未抽样个体分配其分层特定的影响函数
  # 首先，识别出这些未被抽样进入 Phase II 的个体
  phase1_only_dat <- dat[!(dat$id %in% dat2_orig$id), ]
  
  # 从修改后的函数输出中获取分层影响函数矩阵
  H_IS_new_stratified <- IS_new_comp$H_E_phase1_stratified
  H_IP_new_stratified <- IP_new_comp$H_E_phase1_stratified
  
  # 遍历未抽样的个体，并根据其 Y 和 G 分配正确的影响值
  for (i in 1:nrow(phase1_only_dat)) {
    indiv_id <- as.character(phase1_only_dat$id[i])
    indiv_y  <- phase1_only_dat$y[i]
    indiv_g  <- phase1_only_dat$G[i]
    
    # y=0 对应矩阵第1行, y=1 对应第2行
    H_IS_new_total[indiv_id] <- H_IS_new_stratified[indiv_y + 1, indiv_g]
    H_IP_new_total[indiv_id] <- H_IP_new_stratified[indiv_y + 1, indiv_g]
  }
  
  # 4d (新). 为 Phase-II 抽样个体分配其影响函数
  # 这部分逻辑上是为 Phase II 个体赋值，它们的影响函数由 H_E_phase2 决定。
  # Phase-I-only 和 Phase-II 的个体是互斥的，所以可以直接赋值。
  
  # 匹配 Phase-II 的聚合数据和原始个体数据
  key_vars <- colnames(dat2_mle)[!colnames(dat2_mle) %in% c("cases", "conts")]
  dat2_mle$key <- apply(dat2_mle[, key_vars, drop = FALSE], 1, paste, collapse = "_")
  dat2_orig$key <- apply(dat2_orig[, key_vars, drop = FALSE], 1, paste, collapse = "_")
  match_indices <- match(dat2_orig$key, dat2_mle$key)
  
  if (any(is.na(match_indices))) {
    warning("并非所有 Phase-II 个体都被匹配回来计算IDI，方差可能被低估。")
    # 仅保留有效匹配以避免NA错误
    valid_orig_indices <- !is.na(match_indices)
    dat2_orig <- dat2_orig[valid_orig_indices, ]
    match_indices <- na.omit(match_indices)
  }
  
  # 将 Phase-II 个体的影响函数赋值到总影响函数向量的对应位置
  # 在 H_..._new_total 中，这些位置的值当前应为 0
  H_IS_new_total[as.character(dat2_orig$id)] <- IS_new_comp$H_E_phase2[match_indices]
  H_IP_new_total[as.character(dat2_orig$id)] <- IP_new_comp$H_E_phase2[match_indices]
  
  # --- 4e. 计算最终的IDI影响函数 (此部分无变化) ---
  H_IDI_total <- (H_IS_new_total - H_IP_new_total) - (H_IS_old_total - H_IP_old_total)
  
  # --- 5. 计算方差 (此部分无变化) ---
  var_idi <- sum(H_IDI_total^2) / (n_total^2)
  
  return(list(idi = IDI_est, var_idi = var_idi))
  # ======================= 【修改部分结束】 =======================
}



# ==============================================================================
require(plyr) # 确保 plyr 包被加载

Dat_nri_mle_final_corrected <- function(data_list, mleFit_list_new, mleFit_list_old_glm, dat_old) {
  # --- 1. 提取核心对象 (此部分无变化) ---
  dat2_mle <- data_list$dat2.mle
  dat2_orig <- data_list$dat2_orig
  n_total <- nrow(dat_old)
  
  # 新模型 (来自 tps)
  beta_new <- mleFit_list_new$beta.mle
  fhat_new <- mleFit_list_new$f.mle
  p_new <- mleFit_list_new$yhat.mle
  h1_new <- mleFit_list_new$h1
  h2_new <- mleFit_list_new$h2
  df_dbeta_new <- mleFit_list_new$df_beta
  
  # 旧模型 (来自 glm)
  beta_old <- mleFit_list_old_glm$beta.mle
  h_beta_old <- mleFit_list_old_glm$h_beta
  
  # 在与新模型相同的 Phase-II 数据点上计算旧模型的预测概率
  X_matrix_old_for_p <- model.matrix(~x1+x2+x3, dat2_mle)
  p_old <- as.vector(1/(1+exp(-X_matrix_old_for_p %*% beta_old)))
  
  # --- 2. 计算NRI点估计 (此部分无变化) ---
  is_up <- as.integer(p_new > p_old)
  is_down <- as.integer(p_new < p_old)
  
  Py1 <- sum(p_new * fhat_new)
  Py0 <- sum((1 - p_new) * fhat_new)
  
  p_up1 <- if(Py1 > 0) sum(is_up * p_new * fhat_new) / Py1 else 0
  p_down1 <- if(Py1 > 0) sum(is_down * p_new * fhat_new) / Py1 else 0
  p_up0 <- if(Py0 > 0) sum(is_up * (1 - p_new) * fhat_new) / Py0 else 0
  p_down0 <- if(Py0 > 0) sum(is_down * (1 - p_new) * fhat_new) / Py0 else 0
  
  nri_events <- p_up1 - p_down1
  nri_nonevents <- p_down0 - p_up0
  nri_est <- nri_events + nri_nonevents
  
  # --- 3. 数值计算 d(NRI)/d(beta) (此部分无变化) ---
  
  # 3a. 对新模型参数 beta_new 求导
  dNRI_dbeta_new <- numeric(length(beta_new))
  epsilon_new <- abs(beta_new)/1e9; epsilon_new[epsilon_new==0] <- 1e-9
  X_matrix_new <- model.matrix(~x1+x2+x3+z, dat2_mle)
  # ... (求导循环无变化) ...
  for(j in 1:length(beta_new)){
    b_p <- beta_new; b_p[j] <- b_p[j] + epsilon_new[j]
    b_m <- beta_new; b_m[j] <- b_m[j] - epsilon_new[j]
    fhat_p <- fhat_new + df_dbeta_new[j, ] * epsilon_new[j]
    fhat_m <- fhat_new - df_dbeta_new[j, ] * epsilon_new[j]
    p_new_p <- as.vector(1/(1+exp(-X_matrix_new %*% b_p)))
    p_new_m <- as.vector(1/(1+exp(-X_matrix_new %*% b_m)))
    is_up_p <- as.integer(p_new_p > p_old); is_down_p <- as.integer(p_new_p < p_old)
    Py1_p <- sum(p_new_p * fhat_p); Py0_p <- sum((1 - p_new_p) * fhat_p)
    p_u1_p <- if(Py1_p > 0) sum(is_up_p * p_new_p * fhat_p) / Py1_p else 0
    p_d1_p <- if(Py1_p > 0) sum(is_down_p * p_new_p * fhat_p) / Py1_p else 0
    p_u0_p <- if(Py0_p > 0) sum(is_up_p * (1 - p_new_p) * fhat_p) / Py0_p else 0
    p_d0_p <- if(Py0_p > 0) sum(is_down_p * (1 - p_new_p) * fhat_p) / Py0_p else 0
    nri_p <- (p_u1_p - p_d1_p) + (p_d0_p - p_u0_p)
    is_up_m <- as.integer(p_new_m > p_old); is_down_m <- as.integer(p_new_m < p_old)
    Py1_m <- sum(p_new_m * fhat_m); Py0_m <- sum((1 - p_new_m) * fhat_m)
    p_u1_m <- if(Py1_m > 0) sum(is_up_m * p_new_m * fhat_m) / Py1_m else 0
    p_d1_m <- if(Py1_m > 0) sum(is_down_m * p_new_m * fhat_m) / Py1_m else 0
    p_u0_m <- if(Py0_m > 0) sum(is_up_m * (1 - p_new_m) * fhat_m) / Py0_m else 0
    p_d0_m <- if(Py0_m > 0) sum(is_down_m * (1 - p_new_m) * fhat_m) / Py0_m else 0
    nri_m <- (p_u1_m - p_d1_m) + (p_d0_m - p_u0_m)
    dNRI_dbeta_new[j] <- (nri_p - nri_m) / (2 * epsilon_new[j])
  }
  
  # 3b. 对旧模型参数 beta_old 求导
  dNRI_dbeta_old <- numeric(length(beta_old))
  epsilon_old <- abs(beta_old)/1e7; epsilon_old[epsilon_old==0] <- 1e-6
  # ... (求导循环无变化) ...
  for(j in 1:length(beta_old)){
    b_p <- beta_old; b_p[j] <- b_p[j] + epsilon_old[j]
    b_m <- beta_old; b_m[j] <- b_m[j] - epsilon_old[j]
    p_old_p <- as.vector(1/(1+exp(-X_matrix_old_for_p %*% b_p)))
    p_old_m <- as.vector(1/(1+exp(-X_matrix_old_for_p %*% b_m)))
    is_up_p <- as.integer(p_new > p_old_p); is_down_p <- as.integer(p_new < p_old_p)
    is_up_m <- as.integer(p_new > p_old_m); is_down_m <- as.integer(p_new < p_old_m)
    p_u1_p <- if(Py1 > 0) sum(is_up_p * p_new * fhat_new) / Py1 else 0
    p_d1_p <- if(Py1 > 0) sum(is_down_p * p_new * fhat_new) / Py1 else 0
    p_u0_p <- if(Py0 > 0) sum(is_up_p * (1 - p_new) * fhat_new) / Py0 else 0
    p_d0_p <- if(Py0 > 0) sum(is_down_p * (1 - p_new) * fhat_new) / Py0 else 0
    nri_p <- (p_u1_p - p_d1_p) + (p_d0_p - p_u0_p)
    p_u1_m <- if(Py1 > 0) sum(is_up_m * p_new * fhat_new) / Py1 else 0
    p_d1_m <- if(Py1 > 0) sum(is_down_m * p_new * fhat_new) / Py1 else 0
    p_u0_m <- if(Py0 > 0) sum(is_up_m * (1 - p_new) * fhat_new) / Py0 else 0
    p_d0_m <- if(Py0 > 0) sum(is_down_m * (1 - p_new) * fhat_new) / Py0 else 0
    nri_m <- (p_u1_m - p_d1_m) + (p_d0_m - p_u0_m)
    dNRI_dbeta_old[j] <- (nri_p - nri_m) / (2 * epsilon_old[j])
  }
  
  # --- 4. 计算影响函数的所有组件 (此部分无变化) ---
  # a) 来自旧模型glm的影响 (对所有人)
  H_from_beta_old <- as.vector(h_beta_old %*% dNRI_dbeta_old)
  
  # b) 来自新模型tps参数的影响 (for Phase-II)
  H_from_beta_new_p2 <- as.vector(t(h2_new) %*% dNRI_dbeta_new)
  
  # c) 来自新模型非参数分布phi_F的影响
  phi_F_events <- if(Py1 > 0) (fhat_new * n_total / Py1) * p_new * ((is_up - is_down) - nri_events) else 0
  phi_F_nonevents <- if(Py0 > 0) (fhat_new * n_total / Py0) * (1 - p_new) * ((is_down - is_up) - nri_nonevents) else 0
  phi_F_NRI <- phi_F_events + phi_F_nonevents
  
  # ======================= 【修改部分开始】 =======================
  # --- 5. 稳健的N维影响函数重建 ---
  
  # 5.1 初始化总影响函数向量，并加上来自旧模型的不确定性
  H_total_nri <- numeric(n_total)
  names(H_total_nri) <- dat_old$id
  H_total_nri <- H_total_nri + H_from_beta_old
  
  # 5.2 (新) 处理来自新模型 beta_new 对 Phase-I-only 个体的影响
  # 5.2a. 计算每个(Y,G)组合对NRI的影响
  H_from_beta_new_by_group <- as.vector(t(h1_new) %*% dNRI_dbeta_new)
  
  # 5.2b. 创建一个 2xG 矩阵来结构化存储这些影响值
  dat11_info <- plyr::count(dat_old, vars = c("y", "G"))
  numG <- max(dat11_info$G)
  H_beta_new_stratified <- matrix(NA, 
                                  nrow = 2, 
                                  ncol = numG, 
                                  dimnames = list(c("Y=0", "Y=1"), paste0("G=", 1:numG)))
  
  for (i in 1:nrow(dat11_info)) {
    y_val <- dat11_info[i, "y"]
    g_val <- dat11_info[i, "G"]
    H_beta_new_stratified[y_val + 1, g_val] <- H_from_beta_new_by_group[i]
  }
  
  # 5.2c. 识别 Phase-I-only 个体
  phase1_only_dat <- dat_old[!(dat_old$id %in% dat2_orig$id), ]
  
  # 5.2d. 遍历并赋值
  for (i in 1:nrow(phase1_only_dat)) {
    indiv_id <- as.character(phase1_only_dat$id[i])
    indiv_y  <- phase1_only_dat$y[i]
    indiv_g  <- phase1_only_dat$G[i]
    
    # 加上该个体对应的、分层特定的影响值
    H_total_nri[indiv_id] <- H_total_nri[indiv_id] + H_beta_new_stratified[indiv_y + 1, indiv_g]
  }
  
  # 5.3 (新) 处理对 Phase-II 个体的影响
  # 组合来自 beta_new 和 F_hat 的影响
  H_p2_reconstructed <- H_from_beta_new_p2 + phi_F_NRI
  
  # 匹配 Phase-II 的聚合数据和原始个体数据
  key_vars <- colnames(dat2_mle)[!colnames(dat2_mle) %in% c("cases", "conts")]
  dat2_mle$key <- apply(dat2_mle[, key_vars, drop = FALSE], 1, paste, collapse = "_")
  dat2_orig$key <- apply(dat2_orig[, key_vars, drop = FALSE], 1, paste, collapse = "_")
  match_indices <- match(dat2_orig$key, dat2_mle$key)
  
  if(any(is.na(match_indices))){
    warning("并非所有 Phase-II 个体都被匹配回来计算NRI，方差可能被低估。")
    valid_indices <- !is.na(match_indices)
    dat2_orig <- dat2_orig[valid_indices, ]
    match_indices <- na.omit(match_indices)
  }
  
  # 将影响值“广播”给原始 Phase-II 个体，并加到总影响函数中
  H_p2_broadcasted <- H_p2_reconstructed[match_indices]
  H_total_nri[as.character(dat2_orig$id)] <- H_total_nri[as.character(dat2_orig$id)] + H_p2_broadcasted
  
  # --- 6. 计算方差 (此部分无变化) ---
  var_nri <- sum(H_total_nri^2) / (n_total^2)
  if (!is.na(var_nri) && var_nri > 4) {
    var_nri <- NA
  }
  return(list(nri = nri_est, var_nri = var_nri))
  # ======================= 【修改部分结束】 =======================
}

# 2.1 calculate pcf by fitting the maximum likelihood model (新增)
Dat_pcf_mle <- function(q, data_list, mleFit_list){
  #q: threshold value for calculating PCF
  #data_list: generated by Dat_format("MLE");
  fdat.mle <- data_list$fdat.mle
  dat <- data_list$dat
  dat1.mle <- data_list$dat1.mle
  dat2.mle <- data_list$dat2.mle
  
  #mleFit_list: generated by Dat_mleFit(data_list)
  fhat.mle <- mleFit_list$f.mle
  yhat.mle <- mleFit_list$yhat.mle
  beta.mle <- mleFit_list$beta.mle
  numbeta <- length(beta.mle) # 从模型中获取beta数量
  # influence function for odds ratio
  h1 <- mleFit_list$h1
  h2 <- mleFit_list$h2
  strata_mat <- mleFit_list$strata_mat
  df_beta <- mleFit_list$df_beta
  
  #calculate pcf(q)
  q.mat <- data.frame(cbind(yhat.mle, fhat.mle*n))
  names(q.mat) <- c("yhat.mle", "w")
  q.mat <- q.mat[order(-q.mat$yhat.mle),]
  quantile.mle <- cumsum(q.mat$w)/n
  indices <- which((quantile.mle<=q+0.05) & (quantile.mle>=q))
  # 处理当indices为空时的情况
  if (length(indices) == 0) {
    # 如果找不到精确匹配，可以选择最接近的值
    indices <- which.min(abs(quantile.mle - q))
  }
  p0_hat <- max(q.mat[indices, "yhat.mle"])
  
  # calculate pcf
  num_pcf <- sum((yhat.mle*fhat.mle)[yhat.mle>=p0_hat])
  denom_pcf <- sum(yhat.mle*fhat.mle)
  pcf <- num_pcf/denom_pcf
  
  # numerically calcualte dPCF/dbeta
  # 注意：epsilon_beta需要从全局环境中获取，或者作为参数传入
  dT_beta<- numeric(numbeta)
  yfit1 <- numeric(nrow(dat2.mle))
  yfit2 <- numeric(nrow(dat2.mle))
  fhat1 <- numeric(nrow(dat2.mle))
  fhat2 <- numeric(nrow(dat2.mle))
  X <- cbind(rep(1,nrow(dat2.mle)), dat2.mle$x1, dat2.mle$x2, dat2.mle$x3, dat2.mle$z) #Design matrix
  for (i in 1:numbeta){
    tmp1 <- beta.mle
    tmp2 <- beta.mle
    tmp1[i] <- beta.mle[i] + epsilon_beta[i]
    tmp2[i] <- beta.mle[i] - epsilon_beta[i]
    yfit1 <- exp(X %*% tmp1)/(1 + exp(X %*% tmp1))
    yfit2 <-  exp(X %*% tmp2)/(1 + exp(X %*% tmp2))
    fhat1 <- fhat.mle + df_beta[i,]*epsilon_beta[i]
    fhat2 <- fhat.mle - df_beta[i,]*epsilon_beta[i]
    q.mat1 <- data.frame(cbind(yfit1, fhat1*n))
    q.mat2 <- data.frame(cbind(yfit2, fhat2*n))
    names(q.mat1) <- c("yfit1", "w1")
    names(q.mat2) <- c("yfit2", "w2")
    q.mat1 <- q.mat1[order(-q.mat1$yfit1),]
    q.mat2 <- q.mat2[order(-q.mat2$yfit2),]
    quantile1.mle <- cumsum(q.mat1$w1)/n
    quantile2.mle <- cumsum(q.mat2$w2)/n
    indices1 <- which((quantile1.mle<=q+0.05) & (quantile1.mle>=q))
    indices2 <- which((quantile2.mle<=q+0.05) & (quantile2.mle>=q))
    if (length(indices1) == 0) indices1 <- which.min(abs(quantile1.mle - q))
    if (length(indices2) == 0) indices2 <- which.min(abs(quantile2.mle - q))
    p01 <- max(q.mat1[indices1,"yfit1"])
    p02 <- max(q.mat2[indices2,"yfit2"])
    
    num1 <- sum((yfit1*fhat1)[yfit1>=p01])
    num2 <- sum((yfit2*fhat2)[yfit2>=p02])
    denom1 <- sum(yfit1*fhat1)
    denom2 <- sum(yfit2*fhat2)
    dT_beta[i] <- (num1/denom1-num2/denom2)/(2*epsilon_beta[i])
  }
  
  #Calculate influence function for T(Risk distribution at F_inverse(1-q))
  phi <- (p0_hat*(1-q)-yhat.mle*(1-pcf)-(p0_hat-yhat.mle)*as.numeric(yhat.mle<=p0_hat))/denom_pcf
  
  # calcualte the variance of pcf
  a <- rep(as.vector(apply(h1, 2, function(x) x %*% dT_beta)), c(strata_mat[4, ], strata_mat[3, ]))
  b <- rep(as.vector(apply(h2, 2, function(x) x %*% dT_beta)), dat2.mle$cases+dat2.mle$conts)
  c <- rep(-phi, dat2.mle$cases+dat2.mle$conts)
  temp1 <- c(a, b)
  temp2 <- c(rep(0,length(a)), c)
  var_pcf <- t(temp1+temp2) %*% (temp1+temp2)/n^2
  
  return(list(pcf=pcf, var_pcf=var_pcf))
}

Dat_pcf_mle_old <- function(q, data, fullFit_list, X){
  #q: threshold for calculating pcf
  #fullFit_list: generated by Dat_fullFit(data)
  h1 <- fullFit_list$h1
  h0 <- fullFit_list$h0
  yhat.full <- fullFit_list$yhat.full
  beta.full <- fullFit_list$beta.full
  numbeta <- length(beta.full)
  epsilon_beta <- abs(beta_true[1:4])/5
  #calculate pcf(q)
  quantile.full <- quantile(yhat.full, probs=c(0,1-q,1))
  
  p0_hat <- quantile.full[2]
  #sum(yhat.full==p0_hat)
  #num_pcf <- sum(yhat.full[yhat.full>=p0_hat])
  yhat.full.sort <- sort(yhat.full)
  num_pcf <- sum(yhat.full.sort[(round(n*(1-q))):n])
  denom_pcf <- sum(yhat.full)
  pcf <- num_pcf/denom_pcf
  
  ## numerical method for dPCF/dbeta
  dT_beta<- numeric(numbeta)
  yfit1 <- numeric(nrow(data))
  yfit2 <- numeric(nrow(data))
  for (i in 1:numbeta){
    tmp1 <- beta.full
    tmp2 <- beta.full
    tmp1[i] <- beta.full[i] + epsilon_beta[i]
    tmp2[i] <- beta.full[i] - epsilon_beta[i]
    yfit1 <- exp(X %*% tmp1)/(1 + exp(X %*% tmp1))
    yfit2 <-  exp(X %*% tmp2)/(1 + exp(X %*% tmp2))
    #quantile1 <- quantile(yfit1, probs=c(0,1-q,1))
    #quantile2 <- quantile(yfit2, probs=c(0,1-q,1))
    #p01 <- quantile1[2]
    #p02 <- quantile2[2]
    
    #num1 <- sum(yfit1[yfit1>=p01])
    #num2 <- sum(yfit2[yfit2>=p02])
    yfit1.sort <- sort(yfit1)
    yfit2.sort <- sort(yfit2)
    num1 <- sum(yfit1.sort[(round(n*(1-q))):n])
    num2 <- sum(yfit2.sort[(round(n*(1-q))):n])
    denom1 <- sum(yfit1)
    denom2 <- sum(yfit2)
    dT_beta[i] <- (num1/denom1-num2/denom2)/(2*epsilon_beta[i])
  }
  
  #Calculate influence function for T(Risk distribution at F_inverse(1-q))
  phi <- (p0_hat*(1-q)-yhat.full*(1-pcf)-(p0_hat-yhat.full)*as.numeric(yhat.full<=p0_hat))/(denom_pcf/n)
  
  # calculate influence function for PCF at p0_hat
  h1_pcf <- dT_beta %*% h1 - phi
  h0_pcf <- dT_beta %*% h0 - phi
  
  emp_cov_pcf <- sum((h1_pcf)^2*data$y, (h0_pcf)^2*(1-data$y))
  var_pcf <- emp_cov_pcf/n^2
  return(list(pcf=pcf, sq_var_pcf=sqrt(var_pcf)))
}
# 2.2 calculate pnf by fitting the maximum likelihood model (新增)
Dat_pnf_mle <- function(p, data_list, mleFit_list){
  #p: threshold value for calculating PNF
  #data_list: generated by Dat_format("MLE");
  fdat.mle <- data_list$fdat.mle
  dat1.mle <- data_list$dat1.mle
  dat2.mle <- data_list$dat2.mle
  
  #mleFit_list: generated by Dat_mleFit(data_list)
  fhat.mle <- mleFit_list$f.mle
  yhat.mle <- mleFit_list$yhat.mle
  beta.mle <- mleFit_list$beta.mle
  numbeta <- length(beta.mle) # 从模型中获取beta数量
  # influence function for odds ratio
  h1 <- mleFit_list$h1
  h2 <- mleFit_list$h2
  strata_mat <- mleFit_list$strata_mat
  df_beta <- mleFit_list$df_beta
  
  #calculate pnf(q)
  p.mat <- data.frame(cbind(yhat.mle, fhat.mle*n))
  names(p.mat) <- c("yhat.mle", "w")
  p.mat <- p.mat[order(-p.mat$yhat.mle),]
  num.mle <- cumsum(p.mat$yhat.mle*p.mat$w)
  denom.mle <- sum(p.mat$yhat.mle*p.mat$w)
  ratio.mle <- num.mle/denom.mle
  indices <- which((ratio.mle<=p+0.05) & (ratio.mle>=p))
  if (length(indices) == 0) indices <- which.min(abs(ratio.mle - p))
  r_hat <- max(p.mat[indices,"yhat.mle"])
  
  # calculate pnf
  pnf <- sum(fhat.mle[yhat.mle>=r_hat])
  
  # numerically calcualte dPNF/dbeta
  # 注意：epsilon_beta需要从全局环境中获取，或者作为参数传入
  dT_beta<- numeric(numbeta)
  yfit1 <- numeric(nrow(dat2.mle))
  yfit2 <- numeric(nrow(dat2.mle))
  fhat1 <- numeric(nrow(dat2.mle))
  fhat2 <- numeric(nrow(dat2.mle))
  X <- cbind(rep(1,nrow(dat2.mle)), dat2.mle$x1, dat2.mle$x2, dat2.mle$x3, dat2.mle$z) #Design matrix
  for (i in 1:numbeta){
    tmp1 <- beta.mle
    tmp2 <- beta.mle
    tmp1[i] <- beta.mle[i] + epsilon_beta[i]
    tmp2[i] <- beta.mle[i] - epsilon_beta[i]
    yfit1 <- exp(X %*% tmp1)/(1 + exp(X %*% tmp1))
    yfit2 <-  exp(X %*% tmp2)/(1 + exp(X %*% tmp2))
    fhat1 <- fhat.mle + df_beta[i,]*epsilon_beta[i]
    fhat2 <- fhat.mle - df_beta[i,]*epsilon_beta[i]
    p.mat1 <- data.frame(cbind(yfit1, fhat1*n))
    p.mat2 <- data.frame(cbind(yfit2, fhat2*n))
    names(p.mat1) <- c("yfit1", "w1")
    names(p.mat2) <- c("yfit2", "w2")
    p.mat1 <- p.mat1[order(-p.mat1$yfit1),]
    p.mat2 <- p.mat2[order(-p.mat2$yfit2),]
    
    num1 <- cumsum(p.mat1$yfit1*p.mat1$w1)
    num2 <- cumsum(p.mat2$yfit2*p.mat2$w2)
    denom1 <- sum(p.mat1$yfit1*p.mat1$w1)
    denom2 <- sum(p.mat2$yfit2*p.mat2$w2)
    ratio1 <- num1/denom1
    ratio2 <- num2/denom2
    indices1 <- which((ratio1<=p+0.05) & (ratio1>=p))
    indices2 <- which((ratio2<=p+0.05) & (ratio2>=p))
    if (length(indices1) == 0) indices1 <- which.min(abs(ratio1 - p))
    if (length(indices2) == 0) indices2 <- which.min(abs(ratio2 - p))
    r1 <- max(p.mat1[indices1,"yfit1"])
    r2 <- max(p.mat2[indices2,"yfit2"])
    
    pnf1 <- sum(fhat1[yfit1>=r1])
    pnf2 <- sum(fhat2[yfit2>=r2])
    dT_beta[i] <- (pnf1-pnf2)/(2*epsilon_beta[i])
  }
  
  #Calculate influence function for T(Risk distribution at G_inverse(1-p))
  phi <- as.numeric(yhat.mle<=r_hat) + yhat.mle/r_hat*((1-p)-as.numeric(yhat.mle<=r_hat))-(1-pnf)
  
  # calcualte the variance of pnf
  a <- rep(as.vector(apply(h1, 2, function(x) x %*% dT_beta)), c(strata_mat[4, ], strata_mat[3, ]))
  b <- rep(as.vector(apply(h2, 2, function(x) x %*% dT_beta)), (dat2.mle$cases+dat2.mle$conts))
  c <- rep(-phi, (dat2.mle$cases+dat2.mle$conts))
  temp1 <- c(a, b)
  temp2 <- c(rep(0,length(a)), c)
  var_pnf <- t(temp1+temp2) %*% (temp1+temp2)/n^2
  
  return(list(pnf=pnf, var_pnf=var_pnf))
}
Dat_pnf_mle_old <- function(p, data, fullFit_list, X){
  #p: threshold for calculating pnf
  #fullFit_list: generated by Dat_fullFit(data)
  h1 <- fullFit_list$h1
  h0 <- fullFit_list$h0
  yhat.full <- fullFit_list$yhat.full
  beta.full <- fullFit_list$beta.full
  numbeta <- length(beta.full)
  epsilon_beta <- abs(beta_true[1:4])/5
  #calculate pnf(p)
  denom.full <- sum(yhat.full)
  yhat.full.sort <- sort(yhat.full, decreasing=T)
  num.full <- cumsum(yhat.full.sort)
  ratio.full <- num.full/denom.full
  indices <- which((ratio.full<=p+0.05) & (ratio.full>=p))
  r_hat <- max(yhat.full.sort[indices])
  
  #pnf <- sum(yhat.full>=r_hat)/n
  pnf <- as.numeric(indices[1]/n)
  ## numerical method for dPNF/dbeta
  dT_beta<- numeric(numbeta)
  yfit1 <- numeric(nrow(data))
  yfit2 <- numeric(nrow(data))
  for (i in 1:numbeta){
    tmp1 <- beta.full
    tmp2 <- beta.full
    tmp1[i] <- beta.full[i] + epsilon_beta[i]
    tmp2[i] <- beta.full[i] - epsilon_beta[i]
    yfit1 <- exp(X %*% tmp1)/(1 + exp(X %*% tmp1))
    yfit2 <-  exp(X %*% tmp2)/(1 + exp(X %*% tmp2))
    
    denom1 <- sum(yfit1)
    denom2 <- sum(yfit2)
    yfit1.sort <- sort(yfit1, decreasing=T)
    yfit2.sort <- sort(yfit2, decreasing=T)
    num1 <- cumsum(yfit1.sort)
    num2 <- cumsum(yfit2.sort)
    ratio1 <- num1/denom1
    ratio2 <- num2/denom2
    indices1 <- which((ratio1<=p+0.05) & (ratio1>=p))
    indices2 <- which((ratio2<=p+0.05) & (ratio2>=p))
    r1 <- max(yfit1.sort[indices1])
    r2 <- max(yfit2.sort[indices2])
    
    #pnf1 <- sum(yfit1>=r1)/n
    #pnf2 <- sum(yfit2>=r2)/n
    pnf1 <- as.numeric(indices1[1]/n)
    pnf2 <- as.numeric(indices2[1]/n)
    dT_beta[i] <- (pnf1-pnf2)/(2*epsilon_beta[i])
  }
  
  #Calculate influence function for T(Risk distribution at G_inverse(1-p))
  phi <- as.numeric(yhat.full<=r_hat) + yhat.full/r_hat*((1-p)-as.numeric(yhat.full<=r_hat))-(1-pnf)
  
  # calculate influence function for PCF at p0_hat
  h1_pnf <- dT_beta %*% h1 - phi
  h0_pnf <- dT_beta %*% h0 - phi
  
  emp_cov_pnf <- sum((h1_pnf)^2*data$y, (h0_pnf)^2*(1-data$y))
  var_pnf <- emp_cov_pnf/n^2
  return(list(pnf=pnf, sq_var_pnf=sqrt(var_pnf)))
}

calculate_empirical_auc_variance <- function(auc_results_matrix) {
  auc_values_from_simulations <- auc_results_matrix[, 1]
  auc_values_from_simulations <- auc_values_from_simulations[!is.na(auc_values_from_simulations)]
  empirical_variance <- var(auc_values_from_simulations)
  return(empirical_variance)
}

# 新增PCF经验方差函数
calculate_empirical_pcf_variance <- function(pcf_results_matrix) {
  pcf_values_from_simulations <- pcf_results_matrix[, 1]
  pcf_values_from_simulations <- pcf_values_from_simulations[!is.na(pcf_values_from_simulations)]
  empirical_variance <- var(pcf_values_from_simulations)
  return(empirical_variance)
}

# 新增PNF经验方差函数
calculate_empirical_pnf_variance <- function(pnf_results_matrix) {
  pnf_values_from_simulations <- pnf_results_matrix[, 1]
  pnf_values_from_simulations <- pnf_values_from_simulations[!is.na(pnf_values_from_simulations)]
  empirical_variance <- var(pnf_values_from_simulations)
  return(empirical_variance)
}

# 2.4 SNB 计算函数 (全抽样 / 旧模型)
# ==============================================================================
Dat_snb_mle_old <- function(t, dat, fullFit_list, X){
  n <- nrow(dat)
  yhat <- fullFit_list$yhat.full
  h_beta_all <- fullFit_list$h_beta_all # 所有样本的 Beta 影响函数 (p x n)
  
  # 1. 点估计
  pi_est <- mean(yhat)
  ind <- as.numeric(yhat >= t)
  
  tpr_est <- sum(yhat * ind) / sum(yhat)
  fpr_est <- sum((1 - yhat) * ind) / sum(1 - yhat)
  
  weight <- (1 - pi_est) / pi_est * (t / (1 - t))
  snb_est <- tpr_est - weight * fpr_est
  
  # 2. 数值微分 dSNB/dbeta
  beta.full <- fullFit_list$beta.full
  numbeta <- length(beta.full)
  dSNB_beta <- numeric(numbeta)
  epsilon_beta <- abs(beta.full) / 1000
  epsilon_beta[epsilon_beta == 0] <- 0.001
  
  for(i in 1:numbeta){
    b_p <- beta.full; b_p[i] <- b_p[i] + epsilon_beta[i]
    b_m <- beta.full; b_m[i] <- b_m[i] - epsilon_beta[i]
    
    y_p <- exp(X %*% b_p) / (1 + exp(X %*% b_p))
    y_m <- exp(X %*% b_m) / (1 + exp(X %*% b_m))
    
    pi_p <- mean(y_p)
    tpr_p <- sum(y_p * (y_p >= t)) / sum(y_p)
    fpr_p <- sum((1-y_p) * (y_p >= t)) / sum(1-y_p)
    w_p <- (1-pi_p)/pi_p * (t/(1-t))
    snb_p <- tpr_p - w_p * fpr_p
    
    pi_m <- mean(y_m)
    tpr_m <- sum(y_m * (y_m >= t)) / sum(y_m)
    fpr_m <- sum((1-y_m) * (y_m >= t)) / sum(1-y_m)
    w_m <- (1-pi_m)/pi_m * (t/(1-t))
    snb_m <- tpr_m - w_m * fpr_m
    
    dSNB_beta[i] <- (snb_p - snb_m) / (2 * epsilon_beta[i])
  }
  
  # 3. 计算经验分布下的影响函数 (Phi)
  phi_tpr <- yhat * (ind - tpr_est) / pi_est
  phi_fpr <- (1 - yhat) * (ind - fpr_est) / (1 - pi_est)
  phi_pi <- (yhat - pi_est)
  
  term_pi <- (weight * fpr_est / (pi_est * (1 - pi_est))) * phi_pi
  
  phi_snb <- phi_tpr - weight * phi_fpr + term_pi
  
  # 4. 总影响函数
  # h_beta_all 是 (p x n) 矩阵, t(h_beta_all) 是 (n x p)
  h_snb <- as.vector(t(h_beta_all) %*% dSNB_beta) + phi_snb
  
  var_snb <- sum(h_snb^2) / n^2 # 或 var(h_snb)/n
  
  return(list(snb = snb_est, var_snb = var_snb))
}
