# Dat_gen function 
Dat_gen <- function(n, beta, Rho){
  #n: total number of subjects in phase I
  #beta: log odds ratio
  #theta: known odds ratios for x1,x2,x3 (Yaqi:no theta?)
  #p0: pre-specified probability of being selected into phase II for Y=0,G=g (Yaqi:G=g?)
  #ratio: pre-specified number of controls relative to cases
  # Phase I sample
  if (Rho == "Independent")
  {x1 <- rnorm(n)
  z <- rnorm(n)}
  if (Rho == "0.3")
  {sigma <- matrix(c(1, 0.3, 0.3, 1), nrow=2, byrow=TRUE) #0.3*sqrt(1)*sqrt(1)
  x1z <- rmvnorm(n, mean=c(0, 0), sigma=sigma)
  x1 <- x1z[,1]
  z <- x1z[,2]
  #cor(x1,z)
  }
  if (Rho == "0.5")
  {sigma <- matrix(c(1, 0.5, 0.5, 1), nrow=2, byrow=TRUE)
  x1z <- rmvnorm(n, mean=c(0, 0), sigma=sigma)
  x1 <- x1z[,1]
  z <- x1z[,2]
  #cor(x1,z)
  }
  x2 <- runif(n)
  x3 <- rbinom(n, size=1, prob=0.2)
  X <- cbind(rep(1,n), x1, x2, x3, z)
  y <- rbinom(n, size=1, prob=exp(X %*% beta)/(1+exp(X %*% beta)))
  dat <- data.frame(cbind(y,x1,x2,x3,z))
  dat$id <- 1:n
  dat_case <- dat[dat$y==1, ]
  dat_con <- dat[dat$y==0, ]
  dat_ol <- dat[, c("y", "x1", "x2", "x3", "id")]
  dat_ol_case <- dat_ol[dat_ol$y==1, ]
  dat_ol_con <- dat_ol[dat_ol$y==0, ]
  return(list(dat = dat, dat_ol = dat_ol))
}

#2.3 Generate Phase II data with E-balanced Design
Dat_genR <- function(dat, n, beta, numG, p0, ratio){
  #n: total number of subjects in phase I
  #beta: odds ratio
  #numG: number of stratum defined by variables x1,x2,x3
  #p0: pre-specified probability of being selected into phase II for Y=0,G=g
  #ratio: pre-spefified number of controls relative to cases
  dat_case <- dat[dat$y==1, ]
  dat_con <- dat[dat$y==0, ]
  # Phase II sample
  dat2_con <- NULL
  x0 <- xtabs(~dat$y+dat$G)[2,]*ratio
  for (i in 1:numG){
    dat_con_i <- dat_con[dat_con$G==i, ]
    selected_con <- 0
    tot_con <- 1
    ## controls for stratum G=i
    while (tot_con <= nrow(dat_con_i) & selected_con < x0[i]){
      choice <- rbinom(1, size=1, prob=p0[i])
      if (choice==1){
        dat2_con <- rbind(dat2_con, dat_con_i[tot_con, ])
        selected_con <- selected_con + 1
      }
      tot_con <- tot_con + 1
    }
  }
  dat2 <- rbind(dat_case, dat2_con)
  dat2
}

#For data with stratum G (e.g. data generated by BD and E-balanced design or G constructed by post-stratification)
Dat_format <- function(dat, dat2, method){
  #data_list: data generated by Dat_gen;
  #method: MLE/PL/Benchmark
  
  if (method=="MLE"){
    nonDeath <- aggregate(1-dat$y, by=list(G=dat$G, x1=dat$x1, x2=dat$x2, x3=dat$x3, z=dat$z), FUN=sum)$x
    dat1.mle <- data.frame(aggregate(dat$y, by=list(G=dat$G, x1=dat$x1, x2=dat$x2, x3=dat$x3, z=dat$z), FUN=sum))
    dat1.mle <- data.frame(cbind(dat1.mle, nonDeath))
    names(dat1.mle) <- c("G","x1","x2","x3","z", "Death","nonDeath")
    
    conts <- aggregate(1-dat2$y, by=list(G=dat2$G, x1=dat2$x1, x2=dat2$x2, x3=dat2$x3, z=dat2$z), FUN=sum)$x
    dat2.mle <- data.frame(aggregate(dat2$y, by=list(G=dat2$G, x1=dat2$x1, x2=dat2$x2, x3=dat2$x3, z=dat2$z), FUN=sum))
    dat2.mle <- data.frame(cbind(dat2.mle, conts))
    names(dat2.mle) <- c("G","x1","x2","x3","z","cases","conts")
    
    # Final = Phase I + Phase II
    fdat.mle <- merge(dat1.mle, dat2.mle, by=c("G","x1","x2","x3","z"), all=T)
    fdat.mle$cases <- ifelse(is.na(fdat.mle$cases), 0, fdat.mle$cases)
    fdat.mle$conts <- ifelse(is.na(fdat.mle$conts), 0, fdat.mle$conts)
    
    # Estimate u_ig = n_ig/N_ig
    nn1 <- aggregate(dat$y, by=list(G=dat$G), FUN=sum)$x
    nn0 <- aggregate(1-dat$y, by=list(G=dat$G), FUN=sum)$x
    n1 <- aggregate(dat2$y, by=list(G=dat2$G), FUN=sum)$x
    n0 <- aggregate(1-dat2$y, by=list(G=dat2$G), FUN=sum)$x
    
    w1 <- round(n1/nn1, 3)
    w0 <- round(n0/nn0, 3)
    mu_1 <- sapply(fdat.mle$G, function(x) w1[x])
    mu_0 <- sapply(fdat.mle$G, function(x) w0[x])
    return(list(fdat.mle=fdat.mle, dat2.mle=dat2.mle, dat1.mle=dat1.mle, dat=dat, w1=w1, w0=w0, mu_1=mu_1, mu_0=mu_0, nn0=nn0, nn1=nn1, n0=n0, n1=n1,  dat2_orig = dat2))
  }
}

#3. Estimation - with G
#Fit Two-Phase maximum likelihood model (With G)
Dat_mleFit_new <- function(data_list){
  # data_list: generated by Dat_format("MLE")
  fdat.mle <- data_list$fdat.mle
  dat2.mle <- data_list$dat2.mle
  dat1.mle <- data_list$dat1.mle
  dat <- data_list$dat
  w1 <- data_list$w1
  w0 <- data_list$w0
  mu_1 <- data_list$mu_1
  mu_0 <- data_list$mu_0
  nn0 <- data_list$nn0
  nn1 <- data_list$nn1
  n0 <- data_list$n0
  n1 <- data_list$n1
  case=fdat.mle$cases
  group=fdat.mle$G
  x=cbind(rep(1,nrow(fdat.mle)),fdat.mle$x1,fdat.mle$x2,fdat.mle$x3,fdat.mle$z)
  N=fdat.mle$cases+fdat.mle$conts
  numbeta <- numbeta_new
  mod <- tps(cbind(cases, conts) ~ x1+x2+x3+z, data=fdat.mle, nn0=nn0, nn1=nn1, group=fdat.mle$G, method="ML", cohort=T)
  #beta.mle <- mod$coef
  beta.mle <- mod$coef
  #XX <- cbind(rep(1,nrow(fdat.mle)), fdat.mle$x1, fdat.mle$x2, fdat.mle$x3, fdat.mle$z) # Design matrix
  #yhat.mle <- exp(XX %*% beta.mle)/(1 + exp(XX %*% beta.mle))
  XX2 <- cbind(rep(1,nrow(dat2.mle)), dat2.mle$x1, dat2.mle$x2, dat2.mle$x3, dat2.mle$z)
  yhat2.mle <- exp(XX2 %*% beta.mle)/(1 + exp(XX2 %*% beta.mle))
  gamma_ig <- matrix(NA, 2, numG)
  for(g in 1:numG)
  {
    gamma_ig[1,g] <- 1
    for(itr in 1:40)
    {
      mm1 <- (n1[g]-gamma_ig[1,g])/(nn1[g]-gamma_ig[1,g])
      mm0 <- (n0[g]+gamma_ig[1,g])/(nn0[g]+gamma_ig[1,g])
      gamma_ig[1,g] <- n1[g]-sum(yhat2.mle[which(dat2.mle$G==g)]*mm1/(mm0*(1-yhat2.mle[which(dat2.mle$G==g)])+yhat2.mle[which(dat2.mle$G==g)]*mm1))
      itr=itr+1
    }
  }
  gamma_ig[2,] <- -gamma_ig[1,]
  
  Q_ig <- matrix(NA, 2, numG)
  for(g in 1:numG)
  {
    Q_ig[1,g] <- (nn1[g]-gamma_ig[1,g])/(nn0[g]+nn1[g])
    Q_ig[2,g] <- (nn0[g]-gamma_ig[2,g])/(nn0[g]+nn1[g])
  }
  dat11.mle <- data.frame(count(dat, vars=c("y", "G")))
  
  strata_mat <- matrix(NA, 4, numG)
  for (g in 1:numG)
  {strata_mat[1,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$cases==1))
  strata_mat[2,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$conts==1))
  strata_mat[3,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$Death-fdat.mle$cases==1))
  strata_mat[4,g] <- sum(1*(fdat.mle$G==g)*(fdat.mle$nonDeath-fdat.mle$conts==1))}
  
  u_ig <- matrix(NA, 2, numG)
  for (i in 1:2){
    for (g in 1:numG){
      u_ig[i, g] <- 1 - strata_mat[i+2, g]/(sum(strata_mat[,g])*Q_ig[i, g])
      
    }
  }
  
  # All things that we need to calculate based on above information obtained 
  W_g <- numeric(numG)
  B_g <- matrix(NA, numbeta, numG)
  A_g <- matrix(NA, 2, numG)
  p_g <- numeric(numG) #p(G=g)
  for (g in 1:numG){
    #counts <- dat2.mle[dat2.mle$G==g, "counts"]
    counts <- dat2.mle[dat2.mle$G==g, "cases"] + dat2.mle[dat2.mle$G==g, "conts"]
    x1 <- dat2.mle[dat2.mle$G==g, "x1"]
    x2 <- dat2.mle[dat2.mle$G==g, "x2"]
    x3 <- dat2.mle[dat2.mle$G==g, "x3"]
    z <- dat2.mle[dat2.mle$G==g, "z"]
    X <- cbind(rep(1,length(x1)),x1,x2,x3,z) 
    yfit.mle <- yhat2.mle[dat2.mle$G==g]
    u <- c(u_ig[1, g], u_ig[2, g])
    ystar.mle <- u[1]*yfit.mle/(u[1]*yfit.mle+u[2]*(1-yfit.mle))
    
    #W_g
    W_g[g] <- sum(counts*(ystar.mle*(1-ystar.mle)))
    #B_g
    B_g[, g] <- t(X) %*% (counts*ystar.mle*(1-ystar.mle))
    #A_g
    A_g[, g] <- c(1/(strata_mat[1,g]-gamma_ig[1,g])-1/(strata_mat[1,g]+strata_mat[3,g]-gamma_ig[1,g]),
                  1/(strata_mat[2,g]-gamma_ig[2,g])-1/(strata_mat[2,g]+strata_mat[4,g]-gamma_ig[2,g]))    
    #p_g
    p_g[g] <- sum(strata_mat[, g])/sum(strata_mat)
  }
  
  A_0g <- apply(A_g, 2, sum)
  K_g <- 1/A_0g-W_g
  dgamma_1g <- matrix(NA, numbeta, numG)
  for (g in 1:numG){
    dgamma_1g[,g] <- -B_g[,g]/(1-A_0g[g]*W_g[g])
  }
  
  #covariate distribution NPMLE estimates for each strata: f(x1,x2,x3,z,g)=f(x1,x2,x3,z|g)*p(G=g)
  #since x1,x2 are continuous, each unique value will only be counted once
  #f(x1,x2,x3,z,g) is a function of beta
  f.mle <- numeric(nrow(dat2.mle))
  df_g <- matrix(NA, numbeta, nrow(dat2.mle)) #df(x1,x2,x3,z|g)/dbeta 
  df <- matrix(NA, numbeta, nrow(dat2.mle)) #df(x1,x2,x3,z)/dbeta
  s_2 <- matrix(NA, numbeta, nrow(dat2.mle)) #score for R_k=1
  for (k in 1:nrow(dat2.mle)){
    #y <- dat2.mle[k, "y"]
    y <- dat2.mle[k, "cases"]
    x1 <- dat2.mle[k, "x1"]
    x2 <- dat2.mle[k, "x2"]
    x3 <- dat2.mle[k, "x3"]
    z <- dat2.mle[k, "z"]
    #counts <- dat2.mle[k, "counts"]
    counts <- dat2.mle[k, "cases"] + dat2.mle[k, "conts"]
    g <- dat2.mle[k,"G"]
    u <- c(u_ig[1, g], u_ig[2,g])
    yfit.mle <- yhat2.mle[k]
    dgamma <- dgamma_1g[, g]
    a <- A_g[,g]
    f.mle[k] <- counts/(u[1]*yfit.mle+u[2]*(1-yfit.mle))/n
    df_g[,k] <- -counts/(sum(strata_mat[,g])*(u[1]*yfit.mle+u[2]*(1-yfit.mle))^2)*(c(1,x1,x2,x3,z)*yfit.mle*(1-yfit.mle)*(u[1]-u[2])+dgamma*((1-yfit.mle)*u[2]*a[2]-yfit.mle*u[1]*a[1]))
    df[, k] <- df_g[,k]*p_g[g]
    s_2[, k] <- c(1,x1,x2,x3,z)*(y-yfit.mle) + df_g[, k]/f.mle[k]*p_g[g]
  }
  
  s_1 <- matrix(NA, numbeta, nrow(dat11.mle)) #score for R_k=0
  for (k in 1:nrow(dat11.mle)){
    y <- dat11.mle[k, "y"]
    g <- dat11.mle[k, "G"]
    Q <- NULL
    if (y==1){
      Q = Q_ig[1, g]
      s_1[, k] <- -dgamma_1g[, g]/sum(strata_mat[,g])/Q
    }
    else{
      Q = Q_ig[2, g]
      s_1[,k] <- dgamma_1g[, g]/sum(strata_mat[,g])/Q
    }
  }
  #S_1 <- apply(rbind(s_1, c(strata_mat[4, ], strata_mat[3, ])), 2, function(x) x[1:2]*x[3])
  #S_2 <- apply(rbind(s_2, dat2.mle$cases+dat2.mle$conts), 2, function(x) x[1:2]*x[3])
  #apply(S_2, 1, sum) + apply(S_1, 1, sum)
  
  ## Influence function for odds ratios
  h_1 <- mod$covm %*% s_1*n
  h_2 <- mod$covm %*% s_2*n
  emp_cov <- matrix(0, numbeta, numbeta)
  counts2 <- c(strata_mat[4,], strata_mat[3,])
  for (k in 1:ncol(h_1)){
    emp_cov = emp_cov + h_1[, k] %*% t(h_1[, k])*counts2[k]
  }
  for (k in 1:ncol(h_2)){
    emp_cov = emp_cov + h_2[, k] %*% t(h_2[, k])*(dat2.mle$cases[k]+dat2.mle$conts[k])
  }
  # check emp_cov/(n^2) = mod$covm
  
  return (list(beta.mle=beta.mle, beta.var.mle=diag(mod$covm),beta.var.mle.inf=diag(emp_cov/n^2), h1=h_1, h2=h_2, yhat.mle=yhat2.mle, f.mle=f.mle, df_beta=df, strata_mat=strata_mat))
}

Dat_mleFit_old <- function(dat) {
  n <- nrow(dat)
  
  formula_old <- y ~ x1 + x2 + x3
  mod_old <- glm(formula_old, data = dat, family = binomial(link = "logit"))
  
  beta.full <- coef(mod_old)
  yhat.full <- mod_old$fitted.values
  
  X <- cbind(rep(1, n), dat$x1, dat$x2, dat$x3)
  colnames(X) <- names(beta.full)
  
  S1_beta <- apply(cbind(X, yhat.full), 1, function(row) row[1:4] * (1 - row[5]))
  S0_beta <- apply(cbind(X, yhat.full), 1, function(row) row[1:4] * (0 - row[5]))
  
  W <- diag(as.vector(yhat.full * (1 - yhat.full)))
  I_betabeta <- solve(t(X) %*% W %*% X / n)
  
  h1 <- I_betabeta %*% S1_beta
  h0 <- I_betabeta %*% S0_beta
  
  beta.var.full <- diag(I_betabeta / n)
  
  h_beta_all <- matrix(NA, nrow = length(beta.full), ncol = n)
  h_beta_all[, dat$y == 1] <- h1[, dat$y == 1]
  h_beta_all[, dat$y == 0] <- h0[, dat$y == 0]
  
  h_beta_for_idi_nri <- t(h_beta_all)
  
  return(list(
    h1 = h1,
    h0 = h0,
    yhat.full = yhat.full,
    beta.full = beta.full,
    beta.var.full = beta.var.full,
    model = mod_old,
    beta.mle = beta.full,
    h_beta = h_beta_for_idi_nri,
    h_beta_all = h_beta_all
  ))
}

Dat_snb_mle_new <- function(t, data_list, mleFit_list){
  # t: SNB计算的风险阈值 (Threshold probability)
  
  # 提取数据和模型参数
  dat2.mle <- data_list$dat2.mle
  n <- nrow(data_list$dat) # 第一阶段总样本量
  
  fhat.mle <- mleFit_list$f.mle     # 联合分布估计
  yhat.mle <- mleFit_list$yhat.mle  # 预测风险
  beta.mle <- mleFit_list$beta.mle
  numbeta <- length(beta.mle)
  
  # 提取 Beta 的影响函数 (h1: Phase I non-sampled, h2: Phase II sampled)
  h1 <- mleFit_list$h1
  h2 <- mleFit_list$h2
  strata_mat <- mleFit_list$strata_mat
  df_beta <- mleFit_list$df_beta    # 密度对Beta的导数
  
  # --- 1. 计算点估计: Pi, TPR, FPR, SNB ---
  # 注意：在二阶段半参数模型中，期望需通过积分计算 sum(val * fhat)
  
  # 患病率估计 (Pi)
  pi_est <- sum(yhat.mle * fhat.mle)
  
  # 指示变量 I(p >= t)
  ind <- as.numeric(yhat.mle >= t)
  
  # TPR 和 FPR
  num_tpr <- sum(yhat.mle * fhat.mle * ind)
  tpr_est <- num_tpr / pi_est
  
  num_fpr <- sum((1 - yhat.mle) * fhat.mle * ind)
  fpr_est <- num_fpr / (1 - pi_est)
  
  # 计算权重 Omega (假设 H/B = t/(1-t))
  weight <- (1 - pi_est) / pi_est * (t / (1 - t))
  
  # SNB 点估计
  snb_est <- tpr_est - weight * fpr_est
  
  # --- 2. 数值微分计算 dSNB/dbeta ---
  dSNB_beta <- numeric(numbeta)
  epsilon_beta <- abs(beta.mle) / 1000
  epsilon_beta[epsilon_beta == 0] <- 0.001
  
  # 构造设计矩阵 X (注意顺序需与 dat2.mle 一致)
  X <- cbind(rep(1,nrow(dat2.mle)), dat2.mle$x1, dat2.mle$x2, dat2.mle$x3, dat2.mle$z)
  
  for(i in 1:numbeta){
    # 扰动 Beta
    b_p <- beta.mle; b_p[i] <- b_p[i] + epsilon_beta[i]
    b_m <- beta.mle; b_m[i] <- b_m[i] - epsilon_beta[i]
    
    # 更新预测值 yhat
    y_p <- exp(X %*% b_p) / (1 + exp(X %*% b_p))
    y_m <- exp(X %*% b_m) / (1 + exp(X %*% b_m))
    
    # 更新分布估计 fhat (利用 df_beta)
    f_p <- fhat.mle + df_beta[i, ] * epsilon_beta[i]
    f_m <- fhat.mle - df_beta[i, ] * epsilon_beta[i]
    
    # 重新计算指标 (+)
    pi_p <- sum(y_p * f_p)
    tpr_p <- sum(y_p * f_p * (y_p >= t)) / pi_p
    fpr_p <- sum((1 - y_p) * f_p * (y_p >= t)) / (1 - pi_p)
    w_p <- (1 - pi_p)/pi_p * (t/(1-t))
    snb_p <- tpr_p - w_p * fpr_p
    
    # 重新计算指标 (-)
    pi_m <- sum(y_m * f_m)
    tpr_m <- sum(y_m * f_m * (y_m >= t)) / pi_m
    fpr_m <- sum((1 - y_m) * f_m * (y_m >= t)) / (1 - pi_m)
    w_m <- (1 - pi_m)/pi_m * (t/(1-t))
    snb_m <- tpr_m - w_m * fpr_m
    
    # 中心差分
    dSNB_beta[i] <- (snb_p - snb_m) / (2 * epsilon_beta[i])
  }
  
  # --- 3. 计算非参数分布部分的影响函数 (Phi_F) ---
  # 基于推导公式: Phi_SNB = Phi_TPR - w * Phi_FPR + Term_Pi
  
  # Phi_TPR (对应 h2 部分)
  # 这里的 fhat.mle * n 相当于将密度转换为针对每个观测的概率质量/权重
  phi_tpr <- fhat.mle * n * yhat.mle * (ind - tpr_est) / pi_est
  
  # Phi_FPR
  phi_fpr <- fhat.mle * n * (1 - yhat.mle) * (ind - fpr_est) / (1 - pi_est)
  
  # Phi_Pi (患病率的影响函数)
  phi_pi <- fhat.mle * n * (yhat.mle - pi_est)
  
  # 权重项对 Pi 的导数带来的额外影响
  # dSNB/dpi = w * FPR / (pi * (1-pi))
  term_pi <- (weight * fpr_est / (pi_est * (1 - pi_est))) * phi_pi
  
  # 组合得到 SNB 的分布部分影响函数
  phi_snb <- phi_tpr - weight * phi_fpr + term_pi
  
  # --- 4. 计算总影响函数 ---
  # Phase I (非抽样部分): 仅包含 Beta 参数的不确定性
  h1_snb <- t(h1) %*% dSNB_beta
  
  # Phase II (抽样部分): 包含 Beta 参数 + 非参数分布的不确定性
  h2_snb <- t(h2) %*% dSNB_beta + phi_snb
  
  # --- 5. 计算方差 ---
  # 需要将聚合后的影响函数展开回 N 个样本
  # counts2 对应 Dat_mleFit_new 中 strata_mat 的非抽样计数 (Row 4: nonDeath-conts, Row 3: Death-cases)
  counts_nonsampled <- c(strata_mat[4, ], strata_mat[3, ]) 
  
  # Phase II 数据是聚合形式，需要根据 counts (cases+conts) 展开
  counts_sampled <- dat2.mle$cases + dat2.mle$conts
  
  # 展开向量
  a_expanded <- rep(h1_snb, counts_nonsampled)
  b_expanded <- rep(h2_snb, counts_sampled)
  
  # 合并所有个体的影响函数值
  h_total <- c(a_expanded, b_expanded)
  
  # 经验方差: sum(IF^2) / n^2
  var_snb <- sum(h_total^2) / n^2
  
  return(list(snb = snb_est, var_snb = var_snb))
}