# Dat_gen function 
Dat_gen <- function(n, beta, Rho){
  #n: total number of subjects in phase I
  #beta: log odds ratio
  #theta: known odds ratios for x1,x2,x3 (Yaqi:no theta?)
  #p0: pre-specified probability of being selected into phase II for Y=0,G=g (Yaqi:G=g?)
  #ratio: pre-specified number of controls relative to cases
  # Phase I sample
  if (Rho == "Independent")
  {x1 <- rnorm(n)
  z <- rnorm(n)}
  if (Rho == "0.3")
  {sigma <- matrix(c(1, 0.3, 0.3, 1), nrow=2, byrow=TRUE) #0.3*sqrt(1)*sqrt(1)
  x1z <- rmvnorm(n, mean=c(0, 0), sigma=sigma)
  x1 <- x1z[,1]
  z <- x1z[,2]
  #cor(x1,z)
  }
  if (Rho == "0.5")
  {sigma <- matrix(c(1, 0.5, 0.5, 1), nrow=2, byrow=TRUE)
  x1z <- rmvnorm(n, mean=c(0, 0), sigma=sigma)
  x1 <- x1z[,1]
  z <- x1z[,2]
  #cor(x1,z)
  }
  x2 <- runif(n)
  x3 <- rbinom(n, size=1, prob=0.2)
  X <- cbind(rep(1,n), x1, x2, x3, z)
  y <- rbinom(n, size=1, prob=exp(X %*% beta)/(1+exp(X %*% beta)))
  dat <- data.frame(cbind(y,x1,x2,x3,z))
  dat$id <- 1:n
  dat_case <- dat[dat$y==1, ]
  dat_con <- dat[dat$y==0, ]
  dat_ol <- dat[, c("y", "x1", "x2", "x3", "id")]
  dat_ol_case <- dat_ol[dat_ol$y==1, ]
  dat_ol_con <- dat_ol[dat_ol$y==0, ]
  return(list(dat = dat, dat_ol = dat_ol))
}

# Dat_gencc function

Dat_gencc <- function(dat, n, beta, p0, ratio){
  #n: total number of subjects in phase I
  #beta: odds ratio
  #theta: known odds ratios for x1,x2,x3
  #p0: pre-specified probability of being selected into phase II for Y=0,G=g
  #ratio: pre-spefified number of controls relative to cases
  dat_case <- dat[dat$y==1, ]
  dat_con <- dat[dat$y==0, ]
  # Phase II sample
  dat2_con <- NULL
  x0 <- sum(dat$y)*ratio # Changed sum(y) to sum(dat$y) as 'y' is not directly passed
  selected_con <- 0
  tot_con <- 1
  while (tot_con <= nrow(dat_con) & selected_con < x0){
    choice <- rbinom(1, size=1, prob=p0)
    if (choice==1){
      dat2_con <- rbind(dat2_con, dat_con[tot_con, ])
      selected_con <- selected_con + 1
    }
    tot_con <- tot_con + 1
  }
  dat2 <- rbind(dat_case, dat2_con)
  dat2
}

# Dat_format function (unchanged)

Dat_format <- function(dat, dat2, method){
  #data_list: data generated by Dat_gen;
  #method: MLE/PL/Benchmark
  if (method=="MLE"){
    # For dat1.mle, we group by all covariates present in the raw data
    nonDeath <- aggregate(1-dat$y, by=list(x1=dat$x1, x2=dat$x2, x3=dat$x3, z=dat$z), FUN=sum)$x
    dat1.mle <- data.frame(aggregate(dat$y, by=list(x1=dat$x1, x2=dat$x2, x3=dat$x3, z=dat$z), FUN=sum))
    dat1.mle <- data.frame(cbind(dat1.mle, nonDeath))
    names(dat1.mle) <- c("x1","x2","x3","z", "Death","nonDeath")
    # For dat2.mle, we group by all covariates present in the raw data
    conts <- aggregate(1-dat2$y, by=list(x1=dat2$x1, x2=dat2$x2, x3=dat2$x3, z=dat2$z), FUN=sum)$x
    dat2.mle <- data.frame(aggregate(dat2$y, by=list(x1=dat2$x1, x2=dat2$x2, x3=dat2$x3, z=dat2$z), FUN=sum))
    dat2.mle <- data.frame(cbind(dat2.mle, conts))
    names(dat2.mle) <- c("x1","x2","x3","z","cases","conts")
    # Final = Phase I + Phase II
    fdat.mle <- merge(dat1.mle, dat2.mle, by=c("x1","x2","x3","z"), all=T)
    fdat.mle$cases <- ifelse(is.na(fdat.mle$cases), 0, fdat.mle$cases)
    fdat.mle$conts <- ifelse(is.na(fdat.mle$conts), 0, fdat.mle$conts)
    # Estimate u_i = n_i/N_i
    nn1 <- sum(dat$y)
    nn0 <- sum(1-dat$y)
    n1 <- sum(dat2$y)
    n0 <- sum(1-dat2$y)
    w1 <- round(n1/nn1, 3)
    w0 <- round(n0/nn0, 3)
    mu_1 <- rep(w1, nrow(fdat.mle))
    mu_0 <- rep(w0, nrow(fdat.mle))
    return(list(fdat.mle=fdat.mle, dat2.mle=dat2.mle, dat1.mle=dat1.mle, dat=dat, dat2_orig = dat2, w1=w1, w0=w0, mu_1=mu_1, mu_0=mu_0, nn0=nn0, nn1=nn1, n0=n0, n1=n1))
    #
  }
}

Dat_mleFit_old <- function(dat) {
  n <- nrow(dat)
  
  formula_old <- y ~ x1 + x2 + x3
  mod_old <- glm(formula_old, data = dat, family = binomial(link = "logit"))
  
  beta.full <- coef(mod_old)
  yhat.full <- mod_old$fitted.values
  
  X <- cbind(rep(1, n), dat$x1, dat$x2, dat$x3)
  colnames(X) <- names(beta.full)
  
  S1_beta <- apply(cbind(X, yhat.full), 1, function(row) row[1:4] * (1 - row[5]))
  S0_beta <- apply(cbind(X, yhat.full), 1, function(row) row[1:4] * (0 - row[5]))
  
  W <- diag(as.vector(yhat.full * (1 - yhat.full)))
  I_betabeta <- solve(t(X) %*% W %*% X / n)
  
  h1 <- I_betabeta %*% S1_beta
  h0 <- I_betabeta %*% S0_beta
  
  beta.var.full <- diag(I_betabeta / n)
  
  h_beta_all <- matrix(NA, nrow = length(beta.full), ncol = n)
  h_beta_all[, dat$y == 1] <- h1[, dat$y == 1]
  h_beta_all[, dat$y == 0] <- h0[, dat$y == 0]
  
  h_beta_for_idi_nri <- t(h_beta_all)
  
  return(list(
    h1 = h1,
    h0 = h0,
    yhat.full = yhat.full,
    beta.full = beta.full,
    beta.var.full = beta.var.full,
    model = mod_old,
    beta.mle = beta.full,
    h_beta = h_beta_for_idi_nri,
    h_beta_all = h_beta_all
  ))
}

Dat_mleFit_new <- function(data_list){
  # data_list: generated by Dat_format("MLE")
  fdat.mle <- data_list$fdat.mle
  dat2.mle <- data_list$dat2.mle
  dat1.mle <- data_list$dat1.mle
  dat <- data_list$dat
  w1 <- data_list$w1
  w0 <- data_list$w0
  mu_1 <- data_list$mu_1
  mu_0 <- data_list$mu_0
  nn0 <- data_list$nn0
  nn1 <- data_list$nn1
  n0 <- data_list$n0
  n1 <- data_list$n1
  case=fdat.mle$cases
  formula_str <- "cbind(cases, conts) ~ x1+x2+x3+z"
  # Ensure all columns exist, if z might not be in dat2.mle for some reason
  # (though Dat_format always includes it, this is a good safety check if using raw data)
  design_vars <- c("x1", "x2", "x3", "z")
  formula_obj <- as.formula(formula_str)
  mod <- tps(formula_obj, data=fdat.mle, nn0=nn0, nn1=nn1, group=rep(1,nrow(fdat.mle)), method="ML", cohort=T)
  beta.mle <- mod$coef
  numbeta <- length(beta.mle) # Get numbeta from the fitted model coefficients
  XX2 <- cbind(rep(1,nrow(dat2.mle)), dat2.mle$x1, dat2.mle$x2, dat2.mle$x3, dat2.mle$z)
  yhat2.mle <- exp(XX2 %*% beta.mle)/(1 + exp(XX2 %*% beta.mle))
  gamma_i <- matrix(NA, 2, 1)
  gamma_i[1,] <- 1
  for(itr in 1:40)
  {
    mm1 <- (n1-gamma_i[1])/(nn1-gamma_i[1,])
    mm0 <- (n0+gamma_i[1,])/(nn0+gamma_i[1,])
    gamma_i[1,] <- n1-sum(yhat2.mle*mm1/(mm0*(1-yhat2.mle)+yhat2.mle*mm1))
    itr=itr+1
  }
  gamma_i[2,] <- -gamma_i[1,]
  Q_i <- matrix(NA, 2, 1)
  Q_i[1,] <- (nn1-gamma_i[1,])/(nn0+nn1)
  Q_i[2,] <- (nn0-gamma_i[2,])/(nn0+nn1)
  dat11.mle <- data.frame(count(dat, vars=c("y")))
  strata_mat <- matrix(NA, 4, 1)
  strata_mat[1,] <- n1
  strata_mat[2,] <- n0
  strata_mat[3,] <- nn1-n1
  strata_mat[4,] <- nn0-n0
  u_i <- matrix(NA, 2, 1)
  for (i in 1:2){
    u_i[i, 1] <- 1 - strata_mat[i+2, 1]/(sum(strata_mat[,1])*Q_i[i, 1])
  }
  # All things that we need to calculate based on above information obtained
  W <- 0
  B <- matrix(NA, numbeta, 1)
  A <- matrix(NA, 2, 1)
  counts <- dat2.mle$cases+dat2.mle$conts
  x1 <- dat2.mle$x1
  x2 <- dat2.mle$x2
  x3 <- dat2.mle$x3
  z <- dat2.mle$z # Even if not used in model, 'z' might be part of dat2.mle for f.mle calcs.
  X_for_B <- cbind(rep(1,length(x1)),x1,x2,x3,z)
  u <- c(u_i[1, 1], u_i[2, 1])
  ystar.mle <- u[1]*yhat2.mle/(u[1]*yhat2.mle+u[2]*(1-yhat2.mle))
  #W
  W <- sum(counts*(ystar.mle*(1-ystar.mle)))
  #B
  B[, 1] <- t(X_for_B) %*% (counts*ystar.mle*(1-ystar.mle))
  #A
  A[, 1] <- c(1/(strata_mat[1,1]-gamma_i[1,1])-1/(strata_mat[1,1]+strata_mat[3,1]-gamma_i[1,1]),
              1/(strata_mat[2,1]-gamma_i[2,1])-1/(strata_mat[2,1]+strata_mat[4,1]-gamma_i[2,1]))
  A_0 <- apply(A, 2, sum)
  K <- 1/A_0-W
  dgamma_1 <- matrix(NA, numbeta, 1)
  dgamma_1[,1] <- -B[,1]/(1-A_0*W)
  #covariate distribution NPMLE estimates for each strata: f(x1,x2,x3,z)
  #since x1,x2 are continuous, each unique value will only be counted once
  #f(x1,x2,x3,z) is a function of beta
  f.mle <- numeric(nrow(dat2.mle))
  df <- matrix(NA, numbeta, nrow(dat2.mle)) #df(x1,x2,x3,z)/dbeta
  s_2 <- matrix(NA, numbeta, nrow(dat2.mle)) #score for R_k=1
  X_for_df <- cbind(rep(1,nrow(dat2.mle)),dat2.mle$x1,dat2.mle$x2,dat2.mle$x3,dat2.mle$z)
  for (k in 1:nrow(dat2.mle)){
    y <- dat2.mle[k, "cases"]
    x1 <- dat2.mle[k, "x1"]
    x2 <- dat2.mle[k, "x2"]
    x3 <- dat2.mle[k, "x3"]
    z_val <- dat2.mle[k, "z"] # Keep this for `dat2.mle` even if not in model
    counts <- dat2.mle[k, "cases"]+dat2.mle[k, "conts"]
    u <- c(u_i[1,1], u_i[2,1])
    yfit.mle <- yhat2.mle[k]
    dgamma <- dgamma_1[, 1]
    a <- A[,1]
    f.mle[k] <- counts/(sum(strata_mat[,1])*(u[1]*yfit.mle+u[2]*(1-yfit.mle)))
    # The derivative of the linear predictor with respect to beta: d(X*beta)/d(beta)
    # This part needs to be dynamically adjusted based on 'include_z'
    deriv_linear_predictor <- c(1, x1, x2, x3, z_val)
    df[,k] <- -counts/(sum(strata_mat[,1])*(u[1]*yfit.mle+u[2]*(1-yfit.mle))^2)*(deriv_linear_predictor*yfit.mle*(1-yfit.mle)*(u[1]-u[2])+dgamma*((1-yfit.mle)*u[2]*a[2]-yfit.mle*u[1]*a[1]))
    s_2[, k] <- deriv_linear_predictor*(y-yfit.mle) + df[, k]/f.mle[k]
  }
  s_1 <- matrix(NA, numbeta, nrow(dat11.mle)) #score for R_k=0
  for (k in 1:nrow(dat11.mle)){
    y_phase1 <- dat1.mle[k, "Death"] # Use a different name to avoid confusion with y in s_2 loop
    Q <- NULL
    if (y_phase1==1){
      Q = Q_i[1, 1]
      s_1[, k] <- -dgamma_1[, 1]/sum(strata_mat[,1])/Q
    }
    else{
      Q = Q_i[2, 1]
      s_1[,k] <- dgamma_1[, 1]/sum(strata_mat[,1])/Q
    }
  }
  ## Influence function for odds ratios
  h_1 <- mod$covm %*% s_1 * n
  h_2 <- mod$covm %*% s_2 * n
  emp_cov <- matrix(0, numbeta, numbeta)
  counts2 <- c(strata_mat[4,], strata_mat[3,])
  for (k in 1:ncol(h_1)){
    emp_cov = emp_cov + h_1[, k] %*% t(h_1[, k])*counts2[k]
  }
  for (k in 1:ncol(h_2)){
    emp_cov = emp_cov + h_2[, k] %*% t(h_2[, k])*(dat2.mle$cases[k]+dat2.mle$conts[k])
  }
  # check emp_cov/n^2 = mod$covm
  return (list(beta.mle=beta.mle, beta.var.mle=diag(mod$covm),h1=h_1, h2=h_2, yhat.mle=yhat2.mle, f.mle=f.mle, df_beta=df, strata_mat=strata_mat))
}

# ==============================================================================
#           主函数/主程序 (仅用于简单病例-对照设计的参数估计对比)
# ==============================================================================

# --- 1. 加载与环境设置 ---
require(osDesign)
require(plyr)
require(MESS)
require(mvtnorm)


set.seed(0)

# --- 2. 设置模拟参数 (完全按照您的设定) ---
Prev <- "Moder"
Rho <- "Independent"
ratio <- 1
n <- 3000
if(Prev == "Rare")
{beta_true <- log(c(0.03,0.6,1.6,0.6,1.5))}
if(Prev == "Moder")
{beta_true <- log(c(0.13,0.6,1.6,0.6,1.5))}

numbeta_new <- length(beta_true)
numbeta_old <- length(beta_true) - 1
K <- 100 # 建议使用100次或更多模拟以获得稳定结果

# --- 3. 预计算抽样概率 p0 ---
cat("Pre-calculating sampling probability 'p0' for Case-Control design...\n")
x1_init <- rnorm(n)
x2_init <- runif(n)
x3_init <- rbinom(n, size=1, prob=0.2)
z_init <- rnorm(n)
X_init <- cbind(rep(1,n), x1_init, x2_init, x3_init, z_init)
y_init <- rbinom(n, size=1, prob=exp(X_init %*% beta_true)/(1+exp(X_init %*% beta_true)))
dat_init <- data.frame(cbind(y=y_init,x1=x1_init,x2=x2_init,x3=x3_init,z=z_init))

x0 <- sum(dat_init$y)*ratio
p0 <- round(x0/sum(1-dat_init$y), 3)
cat("Using p0 =", p0, "for case-control sampling.\n\n")

# --- 4. 初始化用于存储beta估计值的矩阵 ---
ResBeta_new <- matrix(NA, K, numbeta_new)
colnames(ResBeta_new) <- c("Intercept", "beta_x1", "beta_x2", "beta_x3", "beta_z")

ResBeta_old <- matrix(NA, K, numbeta_old)
colnames(ResBeta_old) <- c("Intercept", "beta_x1", "beta_x2", "beta_x3")


# --- 5. 开始模拟循环 ---
cat("Starting simulation with K =", K, "iterations...\n")
for(k in 1:K)
{
  tryCatch({
    # --- 步骤 5a: 数据生成与准备 ---
    generated_data <- Dat_gen(n, beta_true, Rho)
    dat <- generated_data$dat
    dat_ol <- generated_data$dat_ol
    
    # 调用简单病例-对照抽样函数
    dat_cc_k <- Dat_gencc(dat, n, beta_true, p0, ratio) 
    
    # 调用非分层版本的数据格式化函数
    dat_mlelist <- Dat_format(dat, dat_cc_k, "MLE") 
    
    # --- 步骤 5b: 拟合新旧模型 ---
    mleFit_list_new <- Dat_mleFit_new(dat_mlelist)
    mleFit_list_old <- Dat_mleFit_old(dat_ol)
    
    # --- 步骤 5c: 存储当前循环的beta估计值 ---
    if (!is.null(mleFit_list_new$beta.mle)) {
      ResBeta_new[k, ] <- mleFit_list_new$beta.mle
    }
    if (!is.null(mleFit_list_old$beta.mle)) {
      ResBeta_old[k, ] <- mleFit_list_old$beta.mle
    }
    
    # 打印进度
    if(k %% 10 == 0)
    {
      cat("Iteration:", k, "completed.\n")
    }
    
  }, error = function(e) {
    # 如果发生错误，打印错误信息和迭代次数
    cat("Error in iteration", k, ":", e$message, "\n")
  })
}

cat("Simulation finished.\n\n")


# --- 6. 结果分析与展示 ---
cat("--- Parameter Estimation Summary (Case-Control Design) ---\n\n")

# 计算多次模拟中，beta估计值的平均值
mean_beta_new <- colMeans(ResBeta_new, na.rm = TRUE)
mean_beta_old <- colMeans(ResBeta_old, na.rm = TRUE)
# --- 新增步骤: 计算beta估计值的方差 ---
# 使用apply函数计算每一列(每个参数)的方差
var_beta_new <- apply(ResBeta_new, 2, var, na.rm = TRUE)
var_beta_old <- apply(ResBeta_old, 2, var, na.rm = TRUE)
# 创建新模型的对比结果
beta_names_new <- c("Intercept", "beta_x1", "beta_x2", "beta_x3", "beta_z")
summary_beta_new <- data.frame(
  Model             = "New Model (with z)",
  Parameter         = beta_names_new,
  True_Value        = beta_true,
  Mean_Estimate     = mean_beta_new,
  Variance_Estimate = var_beta_new, # <-- 将计算出的方差添加到数据框
  Bias              = mean_beta_new - beta_true
)


# 创建旧模型的对比结果
beta_names_old <- c("Intercept", "beta_x1", "beta_x2", "beta_x3")
summary_beta_old <- data.frame(
  Model             = "Old Model (no z)",
  Parameter         = beta_names_old,
  True_Value        = beta_true[1:4],
  Mean_Estimate     = mean_beta_old,
  Variance_Estimate = var_beta_old, # <-- 将计算出的方差添加到数据框
  Bias              = mean_beta_old - beta_true[1:4]
)
# 合并并打印最终的摘要报告
final_summary <- rbind(summary_beta_new, summary_beta_old)

# 调整列的顺序，使Bias在最后，更符合阅读习惯
final_summary <- final_summary[, c("Model", "Parameter", "True_Value", "Mean_Estimate", "Variance_Estimate", "Bias")]

print(final_summary, row.names = FALSE, digits = 4) # 使用digits参数让输出更整洁